// Baza de date cu rețetele din cartea Tefal
const recipesData = {
  1: {
    title: "Fabada asturiana",
    time: "35 min",
    servings: "4 porții",
    ingredients: [
      "600 g fasole boabe",
      "200 g ceapă sau 1 ceapă medie",
      "1 roșie",
      "100 g ardei verde",
      "2 căței de usturoi",
      "160 g șuncă",
      "160 g chorizo",
      "160 g caltaboș",
      "60 ml apă",
    ],
    instructions: [
      "Lăsați la înmuiat boabele de fasole în apă din belsug timp de 8 ore.",
      "Adăugați în vasul de gătit: ceapa (tăiată în sferturi), roșia (curățată de coajă și tocată), 2 căței de usturoi (mărunțiți), ardeiul verde (feliat) și fasolea înmuiată.",
      "Adăugați șunca, chorizo-ul și caltabogul și acoperiți cu apă.",
      "Selectați programul de Gătire sub presiune, Mod mare, setați temporizatorul pe 35 minute și apăsați Start.",
      "Când auziți semnalul sonor, rotiți supapa de pe capac pentru a elibera aburul.",
      "Apăsați Anulare și desfaceți oala sub presiune după eliminarea aburului.",
      "Îndepărtați caltabogul, chorizo-ul și șunca, și tăiați-le în bucăți mici.",
      "Turnați boabele de fasole într-un bol de supă sau în farfurii individuale și acoperiți cu carnea tăiată.",
      "Recomandare: Dacă doriți o supă mai densă, îndepărtați o cantitate din lichid, mixați-o cu două linguri de fasole, după care readăugați-o la tocănița.",
    ],
  },
  2: {
    title: "Midii a la marinera",
    time: "10 min",
    servings: "4 porții",
    ingredients: [
      "1 kg midii",
      "100 g ceapă",
      "2 căței de usturoi",
      "100 g ardei roșu",
      "10 g papricã",
      "2 frunze de dafin",
      "10 g pătrunjel",
      "20 ml vin alb",
      "2 linguri de ulei de măsline",
      "Sare și piper",
    ],
    instructions: [
      "Curățați midiile, îndepărtând firele și frecând scoica cu un burete abraziv pentru a îndepărta toate resturile.",
      "Curățați și tocați usturoiul, ceapa și piperul.",
      "Turnați 2 linguri de ulei în vasul de gătit. Selectați programul Rumenire și apăsați Start.",
      "Când mașina emite un semnal sonor, adăugați legumele tocate. Rumeniți ușor timp de 5 minute sau până când sunt rumenite.",
      "Adăugați midiile curățate, frunzele de dafin, vinul alb și paprica.",
      "Închideți capacul și selectați programul de Gătire sub presiune și setați temporizatorul pentru 5 minute. Apăsați Start.",
      "Când terminarea programului este semnalizată printr-un semnal sonor, rotiți supapa de pe capac pentru a elibera aburul.",
      "Apăsați Anulare și desfaceți oala sub presiune după eliminarea aburului.",
      "Scoateți midiile și amplasați-le într-un vas. Acoperiți-le cu supa rezultată în urma gătirii.",
      "Presărați deasupra pătrunjel proaspăt tocat chiar înainte de servire.",
      "Recomandare: Pentru o aromă mai condimentată, adăugați papricã iute în loc de dulce sau un vârf de praf de ardei iute.",
    ],
  },
  3: {
    title: "Cod cu scoici",
    time: "10 min",
    servings: "4 porții",
    ingredients: [
      "600 g cod",
      "200 g scoici",
      "100 g ceapă sau ½ ceapă",
      "100 g praz",
      "2 căței de usturoi",
      "10 g pătrunjel",
      "20 ml vin alb",
      "2 linguri de ulei de măsline",
      "Sare și piper",
    ],
    instructions: [
      "Curățați și tocați usturoiul, ceapa și prazul.",
      "Turnați 2 linguri de ulei în vasul de gătit. Selectați programul Rumenire și apăsați Start.",
      "Când mașina emite un semnal sonor, adăugați usturoiul tocat, ceapa și prazul.",
      "Apăsați Start. Amestecați timp de 5 minute sau până când sunt gătite. Apăsați Anulare.",
      "Adăugați scoicile (curățate), vinul alb și bucățile de pește (condimentate).",
      "Închideți capacul și selectați programul de Gătire sub presiune, și setați temporizatorul pentru 5 minute. Apăsați Start.",
      "Când terminarea programului este semnalizată printr-un semnal sonor, rotiți supapa de pe capac pentru a elibera aburul.",
      "Apăsați Anulare și desfaceți oala sub presiune după eliminarea aburului.",
      "Serviți bucățile de pește cu scoicile desfăcute deasupra codului.",
      "Adăugați condimente suplimentare, dacă este nevoie, și presărați pătrunjel proaspăt tocat.",
      "Recomandare: Dacă nu doriți să utilizați vin, puteți să-l înlocuiți cu supă de pește. Această rețetă poate fi utilizată și cu alte tipuri de pește alb.",
    ],
  },
  4: {
    title: "Sepie cu cartofi",
    time: "15 min",
    servings: "4 porții",
    ingredients: [
      "800 g sepie",
      "100 g ceapă sau ½ ceapă",
      "400 g cartofi",
      "100 g ardei verde",
      "2 căței de usturoi",
      "10 g pătrunjel",
      "30 ml apă",
      "8 fire de sofran",
      "2 linguri de ulei de măsline",
      "Sare și piper",
    ],
    instructions: [
      "Decojiți și mărunțiți căței de usturoi, ceapa și ardeiul.",
      "Curățați sepia și tăiați-o în bucăți mici.",
      "Turnați 2 linguri de ulei în vasul de gătit. Selectați programul Rumenire și apăsați Start.",
      "După semnalul sonor, adăugați usturoiul tocat, ceapa și ardeiul împreună cu sofranul.",
      "Amestecați bine și când în câtă ușor la îl fel gătite uniform, aproximativ 5 minute.",
      "După terminare, apăsați Anulare.",
      "Adăugați bucățile de sepie și cartofii (curățați de coajă și feliați). Acoperiți cu apă și sărați.",
      "Închideți capacul și selectați programul de Gătire sub presiune și setați temporizatorul pentru 10 minute. Apăsați Start.",
      "Când terminarea programului este semnalizată printr-un semnal sonor, rotiți supapa de pe capac pentru a elibera aburul.",
      "Apăsați Anulare și desfaceți oala sub presiune după eliminarea aburului.",
      "Serviți sepia cu cartofi și presărați cu pătrunjel tocat în ultimul moment.",
      "Recomandare: Această rețetă poate fi utilizată și cu inele de calamar în loc de sepie. Adăugați un praf de paprica sau sofran dacă doriți să fie mai condimentat.",
    ],
  },
  5: {
    title: "Budincă de ciocolată fără făină",
    time: "7 min",
    servings: "4 porții",
    ingredients: [
      "115 g ciocolată semi-dulce, ruptă în bucățele",
      "3 linguri de unt, plus unt suplimentar pentru unserea formelor",
      "2 ouă",
      "¼ ceașcă de zahăr pudră",
      "2 linguri cacao nedulcorată",
      "2 lingurițe de extract de vanilie",
      "Ustensile: Suport de metal • 4 forme, unse cu unt",
    ],
    instructions: [
      "Într-un bol, topiți ciocolata și untul, apoi lăsați-le la răcit.",
      "Bateți ouăle, zahărul și extractul de vanilie până când devin spumoase. Adăugați amestecul de ciocolată peste ouă, apoi adăugați cacaua și amestecați folosina un mixer. Amestecați până totul este bine incorporat.",
      "Umpleți formele unse cu unt pe jumătate.",
      "Turnați 1 ¼ ceașcă de apă în vasul de gătit și amplasați suportul metalic în vas. Amplasați formele (numărul depinde de dimensiunile acestora) pe suportul metalic. Selectați programul de Gătire sub presiune, Mare - Temporizator: 7 minute.",
      "După terminarea gătirii, eliberați presiunea. Deschideți capacul.",
      "Serviți cu frișcă sau cu înghețată de vanilie.",
    ],
  },
  6: {
    title: "Cheesecake",
    time: "27 min",
    servings: "4 porții",
    ingredients: [
      "4 biscuiți cu graham întregi, zdrobiți",
      "2 linguri de unt, topit",
      "230 g brânză topită",
      "½ ceașcă de zahăr",
      "2 ouă, bătute ușor",
      "½ ceașcă de smântână acră",
      "Ustensile: Suport de metal • 6 forme, unse cu unt • Folie de plastic sau de aluminiu, care să poată fi utilizată la temperatura indicată",
    ],
    instructions: [
      "Într-un bol, amestecați biscuiții zdrobiți și untul. Împărțiți amestecul astfel obținut, egal între forme și apăsați amestecul pe fundul formelor. Puneți formele în vasul de gătit. Selectați programul de Coacere la 175 °C Temporizator: 10 minute. Lăsați la răcit.",
      "Combinați toate ingredientele rămase într-un al doilea bol până când sunt omogene, apoi turnați amestecul în formele preparate. Acoperiți fiecare formă cu folie de plastic sau de aluminiu. Turnați 1 ceașcă de apă în vasul de gătit și amplasați suportul metalic în vas. Amplasați formele (numărul depinde de dimensiunile acestora) pe suportul metalic. Selectați programul de Gătire sub presiune, Mică - Temporizator: 17 minute.",
      "După terminarea gătirii, eliberați presiunea. Deschideți capacul.",
      "Lăsați să se răcească înainte de a le servi.",
    ],
  },
  7: {
    title: "Pulpe de miel înăbușite",
    time: "25-30 min",
    servings: "4-6 porții",
    ingredients: [
      "2 roșii tocate",
      "6 pulpe de miel",
      "decupate în stil francez (rugați măcelarul să le taie pentru dumneavoastră)",
      "¼ ceașcă de făină simplă, cu un vârf generos de sare și piper",
      "2 linguri de ulei de măsline",
      "1 ceapă, tocată",
      "3 morcovi, feliați gros",
      "1 cățel de usturoi, decojit",
      "1 lingură de oregano proaspăt tocat",
      "coajă rasă de la 1 lămâie",
      "¾ ceașcă de vin roșu",
      "¼ ceașcă de supă de vită sau de legume",
      "sare și piper proaspăt măcinat",
      "Pentru un sos mai gros: 1 lingură de făină simplă amestecată cu 2 linguri de apă rece (opțional)",
    ],
    instructions: [
      "Ștergeți pulpele cu o cârpă uscată, ușor umezită, apoi dați-le prin făina condimentată, scuturând excesul. Selectați programul Rumenire. Încălziți jumătate din cantitatea de ulei în vasul de gătit și rumeniți pulpele câte două o dată. Îndepărtați și lăsați deoparte.",
      "Adăugați uleiul rămas cu ceapa, morcovul și usturoiul în vasul de gătit și rumeniți timp de 5 minute, amestecând ocazional. Adăugați roșiile, oregano, coaja de lămâie, vinul, supa și lăsați să fiarbă, amestecând bine câteva minute. Repuneți pulpele înapoi în vasul de gătit și condimentați bine. Cu ajutorul unei linguri, turnați puțin sos și legume peste pulpe.",
      "Închideți capacul și blocați-l. Selectați programul de Gătire sub presiune, Mare - Temporizator: 20-25 minute (în funcție de grosimea pulpelor). Eliberați presiunea și deschideți capacul. Îndepărtați cu grijă pulpele de miel din vasul de gătit - carnea ar trebui să se fie foarte fragedă, aproape să se desprindă de os. Dacă doriți ca sosul să fie mai gros, selectați programul Fierbere și amestecați făina și apa câte puțin până la îngroșare.",
    ],
  },
  8: {
    title: "Risotto de dovleac",
    time: "10 min",
    servings: "4 porții",
    ingredients: [
      "3 cești de dovleac",
      "1 ½ ceașcă de orez arborio",
      "1 lingură de unt",
      "2 linguri de ulei de măsline",
      "1 ceapă mică, tocată mărunt",
      "½ ceașcă de vin alb sec",
      "3 ½ cești de supă de pui sau de legume",
      "1 linguriță de frunze de salvie",
      "Sare Kosher",
      "Piper negru proaspăt măcinat",
      "3 linguri de parmezan proaspăt ras",
      "2 linguri de pătrunjel proaspăt tocat",
    ],
    instructions: [
      "Curățați dovleacul de coajă și de semințe, și tăiați-l în cuburi de 1 cm.",
      "Selectați programul Rumenire. Încălziți untul și uleiul în vasul de gătit și adăugați dovleacul și gătiți pentru 3 minute.",
      "Adăugați orezul și amestecați pentru a combina cu dovleacul. Adăugați vinul și amestecați timp de 1 minut. Adăugați supa, condimentați ușor, închideți capacul și blocați-l. Selectați programul Orez (sau Gătire sub presiune.) - Temporizator: 6 minute.",
      "După terminarea gătirii, eliberați presiunea.",
      "Deschideți capacul și amestecați salvia. Selectați programul Fierbere timp de 4 minute, amestecând continuu până când orezul devine fraged, gros și cremos.",
      "Încorporați parmezanul și condimentați după gust. Serviți imediat cu pătrunjel presărat deasupra.",
    ],
  },
  9: {
    title: "Budincă de ovăz cu ananas și mentă",
    time: "5 min",
    servings: "4 porții",
    ingredients: [
      "2 cești de ovăz prefiert sau ovăz clasic",
      "2 ½ cești de apă",
      "3 linguri de zahăr",
      "½ linguriță de scorțișoară",
      "Un vârf de sare",
      "⅓ ceașcă de lapte",
      "1 ceașcă de ananas tăiat în bucăți",
      "2 linguri de mentă proaspătă",
    ],
    instructions: [
      "Pregătiți toate ingredientele. Amestecați ovăzul, zahărul, scorțișoara, sarea și apa în vasul de gătit.",
      "Închideți capacul și supapa de presiune.",
      "Selectați programul Budincă - Temporizator: 5 minute.",
      "Când budinca este gata, eliberați presiunea înainte de a deschide capacul. Deschideți capacul, adăugați laptele și amestecați bine.",
      "Turnați budinca în 4 boluri și presărați ananasul și menta deasupra.",
    ],
  },
  10: {
    title: "Budincă de ovăz",
    time: "20 min",
    servings: "4 porții",
    ingredients: ["½ ceașcă de ovăz", "2 cești de apă", "Un vârf de sare"],
    instructions: [
      "Combinați ingredientele în vasul de gătit. Închideți capacul și supapa de presiune.",
      "Selectați programul Budincă și creșteți durata la 15 minute.",
      "Când Budincă este gata, lăsați-o să se răcească (fără a elibera presiunea) timp de 10 minute.",
      "După această durată, desfaceți supapa de presiune și eliberați aburul. Deschideți capacul, amestecați ovăzul și lăsați să stea 5 minute ca să absoarbă apa.",
      "Sfat: turnați deasupra lapte proaspăt, fructe proaspete sau uscate, nuci mărunțite sau granola, și îndulcitorul dumneavoastră preferat - zahăr brun sau alb, sirop de arțar sau de agave.",
    ],
  },
  11: {
    title: "Humus",
    time: "30 min",
    servings: "4 porții",
    ingredients: [
      "1 ceașcă de boabe de năut lăsată la înmurat timp de minim 12 ore",
      "1 lămâie întreagă, stoarsă",
      "1 linguriță de tahini",
      "1 linguriță de chimen măcinat",
      "4 cești de apă pentru a găti boabele",
      "sare Kosher",
      "piper negru proaspăt măcinat",
    ],
    instructions: [
      "Lăsați boabele de năut la înmurat peste noapte.",
      "Puneți năutul scurs în vasul de gătit cu 4 cești de apă. Selectați programul Tocană/Supă, (sau Gătire sub presiune, Ridicată) - Temporizator: 30 minute (în funcție de tipul și de dimensiunea boabelor).",
      "După terminarea gătirii, eliberați presiunea. Deschideți capacul.",
      "Scurgeți boabele și puneți-le deoparte, păstrați 1 ½ ceașcă din lichidul obținut în urma fierberii.",
      "Puneți boabele într-un bol separat, și și pasați-le cu ajutorul unui mixer vertical. Adăugați sucul de lămâie, tahini și chimenul. Amestecați până la omogeneizare. Adăugați treptat lichidul păstrat în urma fierberii, până obțineți consistența dorită. Condimentați după gust.",
      "Serviți humusul cu pită și legume curățate de coajă (castraveți, morcovi, țelină sau gogoșari) tăiate în felii.",
    ],
  },
  12: {
    title: "Supă cremă de roșii",
    time: "10 min",
    servings: "4 porții",
    ingredients: [
      "1 cutie (800 g) de roșii cubulețe",
      "1 ceapă medie, tăiată",
      "1 ceașcă de sos de roșii",
      "3 linguri de roșii uscate, fără ulei",
      "1 cartof mediu, tăiat cubulețe",
      "1 morcov, tăiat cubulețe",
      "2 fire de busuioc",
      "1 ceașcă de supă de legume",
      "2 linguri de unt",
    ],
    instructions: [
      "Puneți roșiile, ceapa tocată, sosul de roșii, cartoful, mocovul, roșiile uscate și busuiocul, precum și supa de legume în vasul de gătit.",
      "Condimentați cu sare și piper și amestecați toate ingredientele.",
      "Selectați programul Gătire sub presiune, Mică - Temporizator: 10 minute.",
      "Când supa a fiert, eliberați presiunea înainte de a deschide capacul. Deschideți capacul.",
      "Îndepărtați busuiocul și pasați cu ajutorul unui mixer vertical (sau punându-le într-un blender) până când obțineți o textură omogenă și apoi încorporați untul.",
      "Condimentați cu sare și piper. Serviți cu smântână acră.",
    ],
  },
  13: {
    title: "Ratatouille",
    time: "15 min",
    servings: "4 porții",
    ingredients: [
      "1 ceapă, tocată",
      "1 ceașcă de ardei galben, curățat de cotor și semințe și tăiat în cubulețe de 2,5cm",
      "1 ceașcă de ardei roșu, curățat de cotor și semințe și tăiat în cubulețe de 2,5cm",
      "1 ceașcă de ardei verde, curățat de cotor și semințe și tăiat în cubulețe de 2,5cm",
      "1 dovlecel zucchini tăiat în felii de 2,5cm",
      "1 dovlecel, tăiat în felii de 2,5cm",
      "1 vânătă, tăiată în cubulețe de 2,5cm",
      "1 cutie de roșii pasate",
      "1 linguriță de oregano",
      "¼ ceașcă de ulei de măsline",
      "1 ½ linguriță de sare kosher",
      "1 linguriță de piper proaspăt măcinat",
      "2 linguri de busuioc proaspăt",
    ],
    instructions: [
      "Spălați ardeii, îndepărtați cotorul, semințele și tăiați în cuburi. Îndepărtați capetele dovlecelului zucchini, ale dovlecelului și ale vinetei. Ideal, tăiați toate legumele în bucăți de dimensiuni similare.",
      "Selectați programul Rumenire, turnați uleiul în vasul de gătit, adăugați ceapa și ardeii, condimentați ușor și lăsați timp de 3 minute. Apoi, adăugați dovlecelul zucchini, dovlecelul și vânăta, și gătiți încă 5 minute. La sfârșit, adăugați roșiile, puneți capacul și blocați-l. Selectați programul de Gătire sub presiune, Mică - Temporizator: 7 minute.",
      "După terminarea gătirii, eliberați presiunea. Deschideți capacul.",
      "Condimentați după gust.",
      "Notă: acest preparat poate fi servit cu ouă, fie prăjite sau benedict ori poate fi utilizat ca și garnitură pentru carne sau pește.",
    ],
  },
  14: {
    title: "Supă cremă de praz și cartofi",
    time: "8 min",
    servings: "4 porții",
    ingredients: [
      "3 fire de praz mare curățat și tocat",
      "3 cartofi medii",
      "1 ceapă",
      "2 linguri de unt",
      "¼ ceașcă de ulei de măsline",
      "3 cești de supă de pui",
      "1 ceașcă de smântână",
      "½ ceașcă de vin alb",
      "Pătrunjel, tocat (opțional)",
      "Sare kosher",
      "Piper negru proaspăt măcinat",
    ],
    instructions: [
      "Tăiați prazul pe jumătate pe lungime și feliați. Utilizați numai porțiunile albe și verde deschis la culoare, spălați bine. Curățați cartofii de coajă și ceapa, spălați și mărunțiți.",
      "Puneți untul și uleiul în vasul de gătit. Selectați programul Rumenire. Când vasul este încălzit, adăugați prazul, cartofii, ceapa și condimentați cu sare și piper. Selectați programul fierbere la foc mic timp de câteva minute, adăugați vinul. Gătiți până la evaporarea alcoolului, după care adăugați un pic de apă rece cât să acopere puțin legumele. Închideți capacul. Selectați programul Tocană/Supă, Legume (sau Gătire sub presiune, Medie) - Temporizator: 8 minute.",
      "Când utilizați funcția de gătire sub presiune, eliberați presiunea înainte de a deschide capacul.",
      "Deschideți capacul. Îndepărtați legumele gătite într-un bol separat și pasați-le cu ajutorul unui mixer vertical ( sau punându-le într-un blender) până când obțineți o textură omogenă. Adăugați smântâna și puneți sare și piper după gust.",
      "Serviți supa caldă, cu pătrunjel tocat pe deasupra.",
    ],
  },
  15: {
    title: "Supă cremă de dovleac",
    time: "20 min",
    servings: "4 porții",
    ingredients: [
      "4 linguri de ulei de măsline",
      "3 felii de șuncă, feliate subțire",
      "2 tulpini subțiri de praz",
      "1 dovleac curățat de coajă, decupat grosolan",
      "1 tulpină de țelină, tocată mărunt",
      "1 cartof mic, curățat de coajă și mărunțit",
      "4 cești de supă de pui sau de legume",
      "3 boabe de piper negru",
      "Sare Kosher",
      "Piper proaspăt măcinat",
      "1 lingură de unt",
    ],
    instructions: [
      "Puneți 2 linguri de ulei în vasul de gătit, selectați programul Rumenire. Când s-a atins temperatura optimă, adăugați șunca și gătiți până când aceasta devine crocantă, amestecând din când în când. Îndepărtați și lăsați deoparte.",
      "Tăiați prazul pe jumătate pe lungime și tăiați în felii subțiri. Utilizați numai porțiunile albe și verde deschis la culoare, spălați bine. Turnați uleiul rămas în vas și continuați să gătiți pe programul Rumenire. Adăugați prazul, dovleacul, țelina și cartoful, amestecați cu o lingură de lemn timp de 4-5 minute sau până când legumele devin ușor aurii. Adăugați supa, boabele de piper negru și presărați un pic de sare. Închideți capacul. Selectați programul Tocană/Supă, Legume (sau Gătire sub presiune, Medie) - Temporizator: 15 minute.",
      "Când utilizați funcția de gătire sub presiune, eliberați presiunea înainte de a deschide capacul. Deschideți capacul.",
      "Transferați legumele gătite într-un bol și pasați cu ajutorul unui mixer vertical ( sau punându-le într-un blender) până când obțineți o textură omogenă. Condimentați după gust.",
      "Repuneți legumele în vasul de gătit. Porniți programul de Reîncălzire. Adăugați untul și lăsați-l să se topească, după care încorporați-l în supă.",
      "Serviți cu bucățele de șuncă crocantă presărate pe deasupra.",
    ],
  },
  16: {
    title: "File de porc cu ciuperci",
    time: "32 min",
    servings: "4 porții",
    ingredients: [
      "1 kg file de porc",
      "¼ ceașcă de ulei de măsline",
      "1 ceapă tăiată în cubulețe",
      "3 căței de usturoi, decojiți și tocați mărunt",
      "1 ceașcă de vin Marsala",
      "1 ceașcă de supă pui",
      "230 g ciuperci, tăiate în sferturi",
      "2 cești de spanac",
      "Amestec de făină pentru carnea de porc:",
      "2 linguri de făină",
      "1 lingură de praf de usturoi",
      "1 lingură de cimbru uscat",
      "1 lingură de sare",
      "½ lingură de piper proaspăt măcinat",
    ],
    instructions: [
      "Ungeți carnea de porc cu amestecul de făină.",
      "Selectați programul Rumenire. Încălziți uleiul și adăugați carnea de porc, prăjiți pe toate laturile timp de aproximativ 4 minute sau până când aceasta este ușor rumenită. Adăugați ciupercile, ceapa și usturoiul și prăjiți-le împreună cu carnea de porc pentru 2-3 minute suplimentare. Adăugați vinul.",
      "Închideți capacul și blocați-l. Selectați programul de Gătire sub presiune, Mare - Temporizator: 25 minute.",
      "După terminarea gătirii, eliberați presiunea. Deschideți capacul.",
      "Scoateți carnea de porc și puneți-o pe un platou și acoperiți-o cu folie de aluminiu. Adăugați spanacul în supă. Când spanacul este înmuiat, așezați-l pe o farfurie împreună cu ciupercile. Feliați carnea de porc și așezați-o peste ciuperci și spanac, apoi serviți.",
    ],
  },
  17: {
    title: "Friptură de pulpe de pui",
    time: "15 min",
    servings: "4 porții",
    ingredients: [
      "1 lingură de ulei de măsline",
      "8 pulpe de pui",
      "2 căței de usturoi, decojiți și tocați",
      "1 ceapă medie, mărunțită",
      "⅔ ceașcă de sos barbecue",
      "⅔ ceașcă de sos de ardei iute",
      "Sare și piper",
    ],
    instructions: [
      "Selectați programul Rumenire. Încălziți uleiul și prăjiți pulpele de pui timp de aproximativ 6 minute.",
      "Adăugați usturoiul și ceapa. Selectați programul Rumenire - Temporizator: 3 minute.",
      "Adăugați ingredientele rămase și amestecați.",
      "Selectați programul de Gătire sub presiune, Mare - Temporizator: 15 minute.",
      "După terminarea gătirii, eliberați presiunea. Deschideți capacul.",
      "Condimentați cu sare și piper. Serviți.",
    ],
  },
  18: {
    title: "Sos bolognese de carne de vită",
    time: "10 min",
    servings: "4 porții",
    ingredients: [
      "½ lingură de ulei de măsline",
      "3 bucăți de șuncă",
      "2 cepe medii, tocate",
      "2 căței de usturoi, zdrobiți",
      "500 g de carne tocată de vită",
      "500 g de carne tocată de porc",
      "1 morcov, tăiat cubulețe",
      "1 rădăcină de țelină, tăiată în cubulețe",
      "½ ceașcă de vin roșu",
      "230 g pastă de roșii",
      "800 g de roșii zdrobite din conservă, scurse de zeamă",
      "2 lingurițe de oregano uscat",
      "2 lingurițe de busuioc uscat",
      "sare și piper după gust",
      "½ ceașcă de parmezan ras",
      "2 frunze de dafin",
    ],
    instructions: [
      "Selectați programul Rumenire. Încălziți uleiul împreună cu carnea de vită, de porc, șunca, ceapa, morcovul, țelina și usturoiul până când carnea este rumenită.",
      "Desfaceți carnea gătită cu ajutorul unei spatule, după care adăugați ingredientele rămase și amestecați bine.",
      "Selectați programul de Gătire sub presiune, Mare - Temporizator: 10 minute.",
      "După terminarea gătirii, eliberați presiunea. Deschideți capacul.",
      "Condimentați după gust, îndepărtați frunzele de dafin. Serviți împreună cu parmezan suplimentar.",
    ],
  },
  19: {
    title: "Chili con Carne",
    time: "10 min",
    servings: "4 porții",
    ingredients: [
      "1 kg carne tocată de vită degresată",
      "2 cepe tăiate în cubulețe mia",
      "2 căței de usturoi, decojiți și tocați mărunt",
      "2 linguri ulei de măsline",
      "1 lingurită de chimen măcinat",
      "800 g de roșii bucăți din conservă, scurse de zeamă",
      "230 g pastă de roșii",
      "2 conserve de 429 g de fasole roșie, clătită și scursă de zeamă",
      "2 linguri de ardei iute",
      "½ lingurița de ardei iute Ancho",
      "¼ lingurită de ardei iute pudră Cayenne",
      "Sare Kosher",
      "Piper negru proaspăt măcinat",
    ],
    instructions: [
      "Selectați programul Rumenire. Prăjiți ușor carnea de vită în ulei. Condimentați cu puțină sare și piper.",
      "Adăugați ceapa, usturoiul, chimenul, praful de ardei iute, praful de ardei iute Ancho și de Cayenne. Amestecați bine.",
      "Adăugați roșiile, sosul de roșii și fasolea. Amestecați din nou și închideți capacul. Selectați programul de Gătire sub presiune, Mică Temporizator: 10 minute.",
      "După terminarea gătirii, eliberați presiunea. Deschideți capacul. Serviți.",
      "Recomandare: Ca preparatul dumneavoastră să aibă un gust mai picant, puteți adăuga câteva prafuri de Tabasco înainte de a-l servi. Chili con carne poate fi servit singur sau împreună cu orez.",
    ],
  },
  20: {
    title: "Ciorbă de văcuță",
    time: "34 min",
    servings: "6 porții",
    ingredients: [
      "500g carne de vită, tăiată cuburi",
      "3 linguri ulei",
      "2 cepe, tocate mărunt",
      "3 cartofi mici, tăiați cuburi",
      "1 morcov, tăiat rondele",
      "1 ardei gras, tăiat cubulețe",
      "1 țelină mică, tăiată cubulețe",
      "400ml suc de roșii",
      "3 frunze de dafin",
      "1 pastârnac, tocat",
      "100g măzare",
      "100g păstâi",
      "1 lingurița cimbru",
      "1.5 litri de apă",
      "Sare și piper, după gust",
    ],
    instructions: [
      "Adăuga uleiul în oală.",
      "Selectează programul Rumenire. Apasă butonul Start.",
      "După semnalul sonor, adaugă și călește ceapa timp de 5 minute.",
      "Adaugă carnea și mai gătește pentru încă 5 minute. După semnalul sonor, apasă butonul Cancel.",
      "Adaugă toate legumele rămase și 300ml de apă.",
      "Selectează programul Gătiț sub presiune. Apasă butonul Cronometru și setează timpul la 15 minute. Închide capacul și apasă butonul Start. (Pe ecran va apărea o pictogramă circulară care se rotește, iar timpul setat va începe să se scurgă)",
      "După semnalul sonor, apasă butonul de pe capac și eliberează aburul. Apasă butonul Anulare și deschide capacul.",
      "Adaugă apa rămasă, cimbru, sare și piper.",
      "Selectează programul Tocană/Supă. Apasă pe butonul cronometru. Setează timpul la 9 minute. Închide capacul și apasă butonul Start. (Pe ecran va apărea o pictogramă circulară care se rotește, iar timpul setat va începe să se scurgă)",
      "După semnalul sonor, apasă butonul de pe capac și eliberează aburul. Apasă butonul Anulare și deschide capacul.",
    ],
  },
  21: {
    title: "Ciorbă de burtă",
    time: "40 min",
    servings: "4 porții",
    ingredients: [
      "700g burtă",
      "1 rasol de vită",
      "250g smântână",
      "3 linguri oțet",
      "½ căpățână de usturoi",
      "1 pastârnac",
      "½țelină",
      "2 morcovi",
      "2 cepe",
      "3 gălbenușuri",
      "gogosăr murat",
      "sare",
      "2 l apă",
    ],
    instructions: [
      "Puneți în oală burta, rasolul de vită, apa și toate legumele.",
      "Selectați programul Gătire sub presiune, apoi setați timpul la 40 minute. Închideți capacul și apăsați butonul Start. (Pe ecran va apărea o pictogramă circulară care se rotește, iar timpul va începe să se scurgă.)",
      "După semnalul sonor, apăsați butonul de pe capac și eliberați aburul. Apăsați butonul Anulare și deschideți capacul.",
      "Scoațeți rasolul și legumele. Tăiați burta fidelută (dacă nu este tăiată deja).",
      "Amestecați într-un bol smântâna cu gălbenușurile, iar apoi, treptat, adăugați câte un polonic de supă. Mutați întreaga compoziție în oală.",
      "Adăugați oțetul și gogosarul murat tăiat felii.",
    ],
  },
  22: {
    title: "Supă de găină",
    time: "25 min",
    servings: "6 porții",
    ingredients: [
      "700g carne de găină",
      "2 morcov, tăiați rondele",
      "1 pastârnac",
      "1 rădăcină pătrunjel",
      "2 cepe",
      "1 ardei gras",
      "1 țelină mică",
      "fidea",
      "1.5L de apă",
      "sare și piper, după gust",
    ],
    instructions: [
      "Puneți uleiul în oală.",
      "Selectați programul Rumenire și apasă butonul Start.",
      "După semnalul sonor, adăugați ceapa și carnea și căliți timp de 10 minute. După semnalul sonor, apăsați butonul Anulare.",
      "Adăugați toate legumele rămase, fideaua și 1.5l de apă.",
      "Selectați programul Gătire sub presiune și setați timpul la 15 minute. Închideți capacul și apăsați butonul Start. (Pe ecran va apărea o pictogramă circulară care se rotește, iar timpul setat va începe să se scurgă.)",
      "După semnalul sonor, apăsați butonul de pe capac și eliberați aburul. Apăsați butonul Anulare și deschideți capacul.",
      "Serviți cu pătrunjel proaspăt tocat deasupra.",
    ],
  },
  23: {
    title: "Piftie",
    time: "55 min",
    servings: "8 porții",
    ingredients: [
      "1kg rasol de porc",
      "3l apă",
      "1 lingură sare",
      "6 căței de usturoi",
      "2 morcovi",
      "2 cepe",
      "1 țelină",
      "3 frunze de dafin",
      "1 rădăcină pătrunjel",
      "piper boabe",
    ],
    instructions: [
      "Puneți rasolul de porc în oală, împreună cu apa.",
      "Selectați programul Gătire sub presiune și setați timpul la 30 minute. Închideți capacul și apăsați butonul Start. (Pe ecran va apărea o pictogramă circulară care se rotește, iar timpul setat va începe să se scurgă)",
      "După semnalul sonor, apăsați butonul de pe capac și eliberați aburul. Apăsați butonul Anulare și deschideți capacul.",
      "Adăugați legumele întregi.",
      "Selectați programul Pressure Cook și setați timpul la 15 minute. Închideți capacul și apăsați butonul Start. (Pe ecran va apărea o pictogramă circulară care se rotește, iar timpul setat va începe să se scurgă)",
      "După semnalul sonor, apăsați butonul de pe capac și eliberați aburul. Apăsați butonul anulare și deschideți capacul.",
      "Selectați programul Fierbere la foc mic și setați timpul la 10 minute. Închideți capacul și apăsați butonul Start. (Pe ecran va apărea o pictogramă circulară care se rotește,iar timpul setat va începe să se scurgă)",
      "După semnalul sonor, apăsați butonul de pe capac și eliberați aburul. Apăsați butonul Anulare și deschideți capacul.",
      "Îndepărtați carnea de pe oase, scoațeți legumele și strecurați supa, pentru o piftie dară.",
      "Pregătiți bolurile pentru piftie cu rondele din morcovul fiert, frunze de pătrunjel și carnea de porc.",
      "Mutați supa în boluri, iar când aceasta s-a răcit, le puteți pune la frigider.",
    ],
  },
  24: {
    title: "Gulaș de vită",
    time: "25 min",
    servings: "6 porții",
    ingredients: [
      "700g carne de vită, tăiată cuburi",
      "3 linguri ulei",
      "2 cepe roșii, tocate mărunt",
      "4 cartofi mici, tăiați cuburi",
      "2 morcovi, tăiați rondele",
      "3 căței de usturoi",
      "1 lingurița chimen",
      "1 lingură boia",
      "2 frunze de dafin",
      "½ lingură sare",
      "1 conserve de 400g roșii decojite",
      "½ cană vin roșu",
      "½ cană apă",
      "1 ardei iute pentru a-l decora",
    ],
    instructions: [
      "Puneți uleiul în oală.",
      "Selectați programul Rumenire și apăsați butonul Start.",
      "După semnalul sonor, adăugați ceapa și căliți timp de 5 minute.",
      "Adăugați carnea, boiaua, chimenul și gătiți pentru încă 5 minute. După semnalul sonor, apăsați butonul Anulare.",
      "Adăugați restul de ingrediente rămase.",
      "Selectați programul Gătire sub presiune și setați timpul la 15 minute. închideți capacul și apăsați butonul Start. (Pe ecran va apărea o pictogramă circulară care se rotește, iar timpul setat va începe să se scurgă)",
      "După semnalul sonor, apăsați butonul de pe capac și eliberați aburul. Apăsați butonul Anulare și deschideți capacul.",
    ],
  },
  25: {
    title: "Fasole cu ciolân afumat",
    time: "40 min",
    servings: "6 porții",
    ingredients: [
      "700g ciolân afumat, tăiat felii",
      "500g fasole boabe uscată",
      "2 cepe, tocate mărunt",
      "2 morcovi, tăiați rondele",
      "500ml pastă de roșii",
      "3 linguri de ulei",
      "2 foi de dafin",
      "cimbru",
      "1 lingură boia dulce",
      "1 lingurița semințe de chimen",
      "sare și piper, după gust",
    ],
    instructions: [
      "Puneți în oală fasolea spălată și 1.5l apă.",
      "Selectați programul Gătire sub presiune și setați timpul la 20 minute.",
      "Închideți capacul și apăsați butonul Start. (Pe ecran va apărea o pictogramă circulară care se rotește, iar timpul setat va începe să se scurgă)",
      "După semnalul sonor, apăsați butonul de pe capac și eliberați aburul. Apăsați butonul Anulare și deschideți capacul.",
      "Scoațeți fasolea și aruncați apă.",
      "Selectați programul Rumenire. Apăsați butonul Start. După semnalul sonor, adăugați ceapa și căliți-o timp de 5 minute.",
      "Adăugați ciolanul afumat și gătiți-l pentru încă 5 minute. După semnalul sonor, apăsați butonul Anulare.",
      "Adăugați restul de ingrediente rămase, inclusiv fasolea fiartă.",
      "Selectați programul Gătire sub presiune și setați și seteaza timpul la 10 minute. Închideți capacul și apăsați butonul Start. (Pe ecran va apărea o pictogramă circulară care se rotește, iar timpul setat va începe să se scurgă)",
      "După semnalul sonor, apăsați butonul de pe capac și eliberați aburul. Apăsați butonul Anulare și deschideți capacul.",
    ],
  },
  26: {
    title: "Sarmale",
    time: "40 min",
    servings: "25 bucăți",
    ingredients: [
      "500g carne de porc, tocată",
      "100g orez",
      "3 linguri ulei",
      "2 cepe roșii",
      "1 lingură pastă de roșii",
      "500ml suc de roșii",
      "2 vaze murată",
      "piper boabe",
      "2 foi dafin",
      "1 lingurița cimbru",
      "½ lingurița măghiran",
      "1 lingurița boia dulce",
      "sare și piper, după gust",
      "afumătură",
      "ardei iute și mămăligă, pentru servit",
    ],
    instructions: [
      "Puneți uleiul în oală",
      "Selectați programul Rumenire și apăsați butonul Start.",
      "După semnalul sonor, adăugați ceapa și căliți-o timp de 5 minute.",
      "Adăugați orezul, 1 cană de apă, sarea și condimentele și gătiți-le pentru încă 5 minute. După semnalul sonor, apăsați butonul Anulare.",
      "Turnați sosul obținut peste carnea tocată, adăugați cimbru, sare și piper (dacă este nevoie) și amestecați compoziția bine.",
      "Tăiați varza murată fidelută și puneți-o pe fundul oalei. Împachetați sarmalele și puneți-le în oală.",
      "Acoperiți sarmalele cu varza murată tocată și afumătura tăiată feliuțe. Puneți foile de dafin, boabele de piper, sucul de roșii și 1 cană apă.",
      "Selectați programul Gătire sub presiune și setați timpul la 30 minute. Închideți capacul și apăsați butonul Start. (Pe ecran va apărea o pictogramă circulară care se rotește, iar timpul va începe să se scurgă)",
      "După semnalul sonor, apăsați butonul de pe capac și eliberați aburul. Apăsați butonul Anulare și deschideți capacul.",
      "Serviți alături de ardei iute și mămăligă.",
    ],
  },
  27: {
    title: "Varză călită cu afumătură",
    time: "30 min",
    servings: "6 porții",
    ingredients: [
      "1 varză dulce media, tocată fideluta",
      "2 cepe, tocate mărunt",
      "2 căței de usturoi, tocați mărunt",
      "1 ardei capia, tocat cubulețe",
      "300g afumătură",
      "150ml pastă de tomate",
      "3 linguri de ulei",
      "2 foi de dafin",
      "cimbru",
      "1 lingură boia dulce",
      "300ml apă",
      "sare și piper, după gust",
    ],
    instructions: [
      "Puneți uleiul în oală.",
      "Selectați programul Rumenire și apăsați butonul Start.",
      "După semnalul sonor, căliți ceapa și afumătura timp de 10 minute. După semnalul sonor, apăsați butonul Anulare.",
      "Adăugați restul de ingrediente rămase.",
      "Selectați programul Gătire sub presiune și setați timpul la 20 minute. Închideți capacul și apăsați butonul Start. (Pe ecran va apărea o pictogramă circulară care se rotește, iar timpul setat va începe să se scurgă)",
      "După semnalul sonor, apăsați butonul de pe capac și eliberați aburul. Apăsați butonul Anulare și deschideți capacul.",
      "Serviți alături de mămăligă caldă și ardei iute.",
    ],
  },
  28: {
    title: "Ciulama de pui și ciuperci",
    time: "45 min",
    servings: "4 porții",
    ingredients: [
      "700g carne de pui, tăiată cuburi",
      "50ml ulei",
      "100g făină",
      "400ml apă (poate fi omisă dacă se dorește)",
      "250g ciupercă, tăiate felii",
      "400g smântână",
      "2 cepe tocate julien",
      "Sare și piper, după gust",
      "Mămăligă, pentru servit",
    ],
    instructions: [
      "Puneți uleiul în oală.",
      "Selectați programul Rumenire și apăsați butonul Start.",
      "După semnalul sonor adăugați și căliți ceapa timp de 5 minute.",
      "Apoi adăugați carnea de pui și prăjiți-o timp de 5 minute. După aceea, adăugați ciupercile și căliți-le timp de 7-10 minute.",
      "Adăugați făina și amestecați timp de 5 minute (să nu se facă cocoloașe). Încorporați și smântâna, amestecând continuu, timp de încă 5 minute. (se poate adăuga un pic de apă dacă este nevoie)",
      "Apăsați butonul Anulare.",
      "Selectați programul Gătire sub presiune și selectați timpul la 15 minute. Închideți capacul și apăsați butonul Start. (Pe ecran va apărea o pictogramă circulară care se rotește, iar timpul setat va începe să se scurgă)",
      "După semnalul sonor, apăsați butonul de pe capac și eliberați aburul. Apăsați butonul Anulare și deschideți capacul.",
      "Serviți alături de mămăligă caldă.",
    ],
  },
  29: {
    title: "Papricaș de pui",
    time: "35 min",
    servings: "6 porții",
    ingredients: [
      "800g carne de pui",
      "3 linguri ulei",
      "4 cepe, tocate mărunt",
      "2 ardei capia, tocați mărunt",
      "3 căței de usturoi, tocați",
      "250ml apă",
      "2 roșii",
      "2 foi de dafin",
      "2 linguri făină (opțional)",
      "1 lingură boia dulce",
      "sare și piper, după gust",
      "pentru găluște: 2 ouă + 200g făină + 2 linguri ulei + sare",
    ],
    instructions: [
      "Gătușe:",
      "Selectați programul Fierbere la foc mic și setați timpul la 10 minute.",
      "Turnați 1.5l apă în oală. Formați cu o linguriță gălușțele și puneți una câte una în oală.",
      "Închideți capacul și apăsați butonul Start. (Pe ecran va apărea o pictogramă circulară care se rotește, iar timpul setat va începe să se scurgă)",
      "După semnalul sonor, apăsați butonul de pe capac și eliberați aburul. Apăsați butonul Anulare și deschideți capacul.",
      "Scoațeți gălușțele și mențineti-le calde. Aruncați apa.",
      "Papricaș:",
      "Selectați programul Rumenire și apăsați butonul Start. După semnalul sonor, adăugați ceapa și căliți-o timp de 5 minute.",
      "Adăugați carnea și făina (opțional), gătiți-le pentru încă 5 minute. După semnalul sonor, apăsați butonul Anulare. Adăugați restul de ingrediente rămase.",
      "Selectați programul Gătire sub presiune și setați timpul la 15 minute. Închideți capacul și apăsați butonul Start. (Pe ecran va apărea o pictogramă circulară care se rotește, iar timpul setat va începe să se scurgă)",
      "După semnalul sonor, apăsați butonul de pe capac și eliberați aburul. Apăsați butonul Anulare și deschideți capacul.",
      "Adăugați gălușțele, presărați pătrunjelul proaspăt și serviți cald.",
      "Dobaveite knedlite i magdanoš, servirajte gorećo.",
      "Servirajte s polenta.",
    ],
  },
  30: {
    title: "Orez cu lapte",
    time: "20 min",
    servings: "4 porții",
    ingredients: [
      "200g orez",
      "200ml apă",
      "500ml lapte",
      "100g zahăr",
      "1 praf de sare",
      "vanilie",
      "stafide",
    ],
    instructions: [
      "Puneți în oală toate ingredientele.",
      "Selectați programul Gătire sub presiune. Apăsați săgeata în jos și selectați presiunea la nivel medium și setați timpul la 15 - 20 minute. Închideți capacul și apăsați butonul Start. (Pe ecran va apărea o pictogramă circulară care se rotește, iar timpul setat va începe să se scurgă)",
      "După semnalul sonor apăsați, butonul de pe capac și eliberați aburul. Apăsați butonul Anulare și deschideți capacul.",
    ],
  },
  31: {
    title: "Dulceață de piersici",
    time: "30 min",
    servings: "4 porții",
    ingredients: [
      "1kg piersici, fără sâmburi și tocate cuburi",
      "150g zahăr",
      "sucul de la 1 lămâie",
      "esență de vanilie",
      "50ml apă",
    ],
    instructions: [
      "Puneți în oală toate ingredientele.",
      "Selectați programul Gătire sub presiune. Apăsați săgeata în jos și setați presiunea la nivel medium și setați la 10 minute. Închideți capacul și apăsați butonul Start. (Pe ecran va apărea o pictogramă circulară care se rotește, iar timpul setat va începe să se scurgă)",
      "După semnalul sonor, apăsați butonul de pe capac și eliberați aburul. Apăsați butonul Anulare și deschideți capacul.",
      "Selectați programul Fierbere la foc mic și setați timpul la 15 minute. Închideți capacul și apăsați butonul Start. (Pe ecran va apărea o pictogramă circulară care se rotește, iar timpul setat va începe să se scurgă)",
      "După semnalul sonor, apăsați butonul de pe capac și eliberați aburul.",
      "Dacă dulceața este prea lichidă, selectați programul Rumenire pentru încă 10 minute.",
    ],
  },
  32: {
    title: "Limbă cu măsline",
    time: "50 min",
    servings: "6 porții",
    ingredients: [
      "700g limbă de vită",
      "1 morcov",
      "1 țelină",
      "1 pastârnac",
      "piper boabe",
      "1 fir praz",
      "2 linguri ulei",
      "150ml vin roșu",
      "1 frunză dafin",
      "2 căței usturoi",
      "200g măsline negre, fără sâmburi",
      "1 cană apă",
      "2-3 căni apă",
      "adițional",
      "Sare și piper, după gust",
    ],
    instructions: [
      "Puneți limba de vită în oală, împreună cu apa, morcovul, țelina, pâstârnacul și piperul boabe.",
      "Selectați programul Gătire sub presiune și setați timpul la 30 minute. Închideți capacul și apăsați butonul Start. (Pe ecran va apărea o pictogramă circulară care se rotește, iar timpul setat va începe să se scurgă)",
      "După semnalul sonor, apăsați butonul de pe capac și eliberați aburul. Apăsați butonul Anulare și deschideți capacul. Lăsați la răcit carnea și legumele.",
      "Selectați programul Rumenire. Apăsați butonul Start. După semnalul sonor, adăugați prazul și căliți-l timp de 5 minute. Adăugați vinul, usturoiul, pasta de roșii, sarea și apa (sau supă în care s-a fiert limba) și gătiți pentru încă 5 minute. Apăsați butonul Anulare.",
      "Adăugați măslinele și limba (curățată de piele și tăiată felii). Selectați programul Fierbere la foc mic și setați Setează timpul la 10 minute. Închideți capacul și apăsați butonul Start. (Pe ecran va apărea o pictogramă circulară care se rotește, iar timpul setat va începe să se scurgă)",
      "După semnalul sonor, apăsați butonul de pe capac și eliberați aburul. Apăsați butonul anulare și deschideți capacul.",
    ],
  },
  33: {
    title: "Supă gulaș",
    time: "30 min",
    servings: "4 porții",
    ingredients: [
      "200g file din pulpă de vită",
      "200g cartofi",
      "2 frunze de dafin",
      "4 cuișoare englezești",
      "100g ceapă",
      "20g usturoi",
      "1 lingură de paprica dulce",
      "¼ lingură de paprica iute",
      "50g slănină",
      "1 lingură de măghiran",
      "2 linguri de făină",
      "1 litru de apă",
      "sare",
    ],
    instructions: [
      "Tăiați carnea de vită în cubulețe și amestecați-o într-un bol cu sarea, paprica dulce și iute.",
      "Selectați programul Rumenire și adăugați slănina. După activarea temporizatorului, adăugați ceapa tocată mărunt și condimentați cu frunza de defin și cu boabele de cuișoare englezești. Adăugați carnea și gătiți. Presărați făina și continuați să gătiți.",
      "Turnați apa și fierbeți. Închideți capacul și selectați Gătire sub presiune - Temporizator 20 minute.",
      "Adăugați cartofii tăiați și închideți capacul. Selectați programul de Gătire lentă și gătiți pentru încă 10 minute.",
      "După terminarea gătitului, desfaceți capacul, condimentați cu maghiran, usturoi și sare.",
      "Pentru o rețetă fără gluten, înlocuiți făina cu un cartof suplimentar.",
    ],
  },
  34: {
    title: "Supă de pui",
    time: "60 min",
    servings: "4 porții",
    ingredients: [
      "1 pui întreg",
      "200g morcovi",
      "200g țelină",
      "200g rădăcină de pătrunjele",
      "150g ceapă",
      "30g frunze de pătrunjel",
      "2.5 litri de apă",
      "4 frunze de dafin",
      "6 cuișoare englezești",
      "8 boabe de piper întreg",
      "¼ lingurița de nucsoara",
      "sare",
    ],
    instructions: [
      "Tăiați puiul în cuburi.",
      "Selectați programul Rumenire, prăjiți legumele și ceapa până devin aurii.",
      "Adăugați puiul, prăjiți și turnați apa. După care adăugați condimentele, frunzele de pătrunjel și închideți capacul.",
      "Selectați programul de Gătire sub presiune - temporizator: 60 minute.",
      "Deschideți capacul și scoațeți carnea. Dezosiți carnea.",
      "Mixați conținutul vasului, apoi condimentați-l cu nucsoara si adăugați carnea.",
    ],
  },
  35: {
    title: "Ciorbă de cartofi",
    time: "20 min",
    servings: "4 porții",
    ingredients: [
      "200g ceapă",
      "200g morcovi",
      "150g țelină",
      "150g rădăcină de pătrunjel",
      "300g cartofi",
      "8 căței de usturoi",
      "50g ciuperci uscate – înmuiate în apă timp de 1 oră",
      "măghiran",
      "piper proaspăt măcinat",
      "1 lingurița de chimen",
      "4 frunze de dafin",
      "50g de slănină",
      "1.5 litri de apă",
    ],
    instructions: [
      "Tăiați ceapa în sferturi și restul legumelor în cuburi.",
      "Selectați programul Rumenire și topiți slănina. Adăugați toate legumele, chimenul și o frunză de dafin, apoi rumeniți până devin aurii.",
      "Adăugați cartofii tăiați și ciupercile înmuiate împreună cu apa în care au stat. Turnați apa și sărați. Închideți capacul și selectați programul Gătire sub presiune - Temporizator 20 minute.",
      "Adăugați măghiranul, piperul și usturoiul cu sarea.",
      "Această rețetă nu conține gluten și lactoză.",
    ],
  },
  36: {
    title: "Ciorbă de burtă",
    time: "20 min",
    servings: "4 porții",
    ingredients: [
      "400g burtă gătită",
      "400g slănină",
      "2 cepe mari",
      "2 linguri de boia dulce",
      "8 căței de usturoi",
      "sare",
      "piper măcinat",
      "4 frunze de dafin",
      "6 cuișoare englezești",
      "3 linguri de făină (pentru roux)",
      "Să se utilizeze amidon amestecat cu apă la îngroșare",
      "măghiran",
      "1.5 litri de apă",
    ],
    instructions: [
      "Puneți slănina în vasul de gătit, adăugați ceapa tocată mărunt, selectați programul Rumenire. Adăugați cartofii tăiați, piperul, cuișoarele englezești, frunzele de dafin și prăjiți.",
      "Presărați făina și turnați apa. Închideți capacul și selectați programul Gătire sub presiune - Temporizator 20 minute.",
      "Adăugați piperul, usturoiul, sarea și măghiranul.",
      "Puteți prepara o versiune fără gluten înlocuind făina cu amidon amestecat cu apă.",
    ],
  },
  37: {
    title: "Ciorbă de varză cu cârnați",
    time: "20 min",
    servings: "4 porții",
    ingredients: [
      "2 cepe",
      "400g vază murată",
      "6 frunze de dafin",
      "6 cuișoare englezești",
      "1 cartof mare",
      "2 cârnați",
      "50g slănină",
      "2 linguri de paprica dulce",
      "300g smântână acră (sau puteți utiliza smântană fără lactoză)",
      "1.5 litri de apă",
      "sare",
    ],
    instructions: [
      "Tăiați ceapa mărunt și cârnații în semi felii.",
      "Selectați programul Rumenire, topiți slănina și adăugați ceapa și cârnații. Rumeniți până devin aurii.",
      "Adăugați paprica, cartofii tăiați și varza si toate condimentele.",
      "Turnați apa, închideți capacul și selectați programul Gătire sub presiune - temporizator: 20 minute.",
      "Adăugați sare și serviți cu smântână acră.",
    ],
  },
  38: {
    title: "Pui cu paprika",
    time: "15 min",
    servings: "4 porții",
    ingredients: [
      "4 bucăți de piept de pui",
      "3 linguri de paprica",
      "2 cepe mari",
      "3 linguri de făină (pentru o versiune fără gluten puteți utiliza amidon)",
      "1 litru de supă de pui",
      "200 ml smântână de 33%",
      "(utiliza smântână fără lactoză)",
      "50g unt (sau ulei)",
      "sare",
    ],
    instructions: [
      "Puneți cepele tocate fin în vasul de gătit și selectați programul Rumenire. Rumeniți până devin aurii.",
      "Adăugați puiul feliat și prăjiți. Apoi adăugați piperul, făina și prăjiți în continuare.",
      "Adăugați supa și închideți capacul. Selectați programul de Gătire sub presiune - temporizator: 15 minute.",
      "Adăugați smântâna și sarea. Selectați programul Rumenire și gătiți pentru un timp la temperatura de 120 de grade.",
    ],
  },
  39: {
    title: "Gulaș Segedin",
    time: "40 min",
    servings: "4 porții",
    ingredients: [
      "800g pulpă de porc",
      "200g ceapă",
      "300g varză murată",
      "4 frunze de dafin",
      "6 cuișoare englezești",
      "1 lingură de chimen măcinat",
      "1 lingură de praf de paprica dulce",
      "50g slănină",
      "Sare",
      "200ml smântână de 33% (utiliza smântână fără lactoză)",
      "Piper",
      "1 litru de apă",
    ],
    instructions: [
      "Tăiați carnea în bucăți medii, adăugați sarea și amestecați cu piperul și chimenul. Tăiați ceapa în jumătăți.",
      "Selectați programul Rumenire, topiți slănina și adăugați ceapa și prăjiți până devin aurii.",
      "Adăugați carnea, cuișoarele englezești și frunza de dafin și prăjiți în continuare.",
      "Turnați apa și închideți capacul. Porniți Programul de Gătire sub presiune - temporizator: 30 minute.",
      "Adăugați varza și selectați programul de Gătire sub presiune - temporizator: 10 minute.",
      "Deschideți capacul, adăugați sarea și piperul. Apoi încorporați smântâna și fierbeți la 120 de grade un timp.",
    ],
  },
  40: {
    title: "Porc cu morcovi",
    time: "30 min",
    servings: "4 porții",
    ingredients: [
      "600g pulpă de porc",
      "400g morcovi",
      "1 ceapă",
      "50g slănină",
      "3 linguri de făină",
      "2 linguri de zahăr",
      "1 lămâie",
      "700ml apă",
      "Sare",
      "Nucsoara",
      "100ml smântână de 33% (sau puteți utiliza smântână fără lactoză)",
    ],
    instructions: [
      "Feliați ceapa și cartofii.",
      "Selectați programul Rumenire, topiți slănina și adăugați legumele. Rumeniți până devin aurii.",
      "Adăugați zahărul și lăsați-l să se caramelizeze. Presărați făina și continuați să prăjiți. Apoi adăugați carnea tăiată și sarea, continuați să prăjiți.",
      "Turnați apa, închideți capacul și selectați programul Gătire sub presiune - temporizator: 30 minute.",
      "Adăugați sarea, coaja de lămâie și sucul de lămâie împreună cu nucșoara. Încorporați smântâna.",
    ],
  },
  41: {
    title: "Vită în sos de mărar",
    time: "70 min",
    servings: "4 porții",
    ingredients: [
      "600g ceafă de vită",
      "100g ceapă",
      "4 linguri de făină (pentru o versiune fără gluten puteți utiliza amidon)",
      "80g unt (sau puteți utiliza ulei)",
      "200ml smântână de 33% (o puteți înlocui cu smântână fără lactoză)",
      "1 legătură de mărar",
      "2 lămâi",
      "3-4 linguri de zahăr",
      "sare",
      "4 frunze de dafin",
      "6 cuișoare englezești",
      "8 boabe de piper",
      "1.5 litri de apă",
    ],
    instructions: [
      "Tăiați ceafa de vită în cuburi mari și puneți-le în vasul de gătit. Adăugați condimentele, sarea, ceapa și turnați apa.",
      "Închideți capacul și selectați programul Gătire sub presiune - temporizator: 60 minute.",
      "Mutați supa într-un bol și îndepărtați condimentele.",
      "Selectați programul Rumenire și gătiți făina cu untul. Turnați supa la loc în vasul de gătit împreună cu carnea și continuați să gătiți timp de 10 minute suplimentare.",
      "Adăugați sarea, sucul de lămâie, mărarul tocat și smântâna.",
      "Pentru o versiune fără gluten puteți utiliza făină fără gluten. De asemenea, puteți utiliza produse fără lactoză.",
    ],
  },
  42: {
    title: "Gulaș de vită",
    time: "50 min",
    servings: "4 porții",
    ingredients: [
      "800g pulpă de vită",
      "30g slănină",
      "300g ceapă",
      "4 frunze de dafin",
      "1 lingurița de chimen",
      "1 ardei iute",
      "6 cuișoare englezești",
      "2 linguri de paprica dulce",
      "30g piure de roșii",
      "1 cartof mediu",
      "8 căței de usturoi",
      "sare",
      "măghiran",
      "piper",
      "1.5 litri de apă",
    ],
    instructions: [
      "Tăiați carnea de vită în cuburi mari, sărați și amestecați-o într-un bol cu paprica.",
      "Tăiați ceapa mărunt și puneți-o în vasul de gătit. Selectați programul Rumenire și apăsați Start.",
      "Rumeniți slănina cu frunza de dafin, chimenul și cuișoarele englezești. Adăugați piureul de roșii și continuați să gătiți, după care adăugați carnea, ardeiul iute și lăsați la rumenit.",
      "Turnați apa, închideți capacul și selectați programul Gătire sub presiune - temporizator: 40 minute.",
      "Adăugați cartoful tăiat mărunt și condimentați cu usturoi, sare, piper și măghiran.",
      "Selectați programul Rumenire și gătiți la 120 de grade aproximativ 10 minute.",
      "Această rețetă nu conține gluten și lactoză.",
    ],
  },
  43: {
    title: "Tocăniță de vițel",
    time: "25 min",
    servings: "4 porții",
    ingredients: [
      "600 g carne de vițel",
      "2 cepe sau 400 g",
      "4 morcovi sau 250 g",
      "1 ardei roșu sau 250 g",
      "1 ardei verde sau 250 g",
      "2 căței de usturoi",
      "200 g sos de roșii",
      "20 ml vin roșu",
      "2 linguri de ulei de măsline",
      "Sare și piper",
    ],
    instructions: [
      "Puneți 2 linguri de ulei în vasul de gătit. Selectați programul Rumenire și apăsați Start.",
      "După semnalul sonor, adăugați usturoiul tocat, ceapa și ardeiul feliat. Lăsați la înăbușit timp de 5 minute. Când legumele sunt pătrunse, apăsați Anulare.",
      "Adăugați carnea (tăiată în bucățele mici), morcovii feliați, vinul roșu și sosul de roșii.",
      "Condimentați cu sare și piper.",
      "Închideți capacul și selectați programul de Gătire sub presiune și setați temporizatorul pentru 20 minute. Apăsați Start.",
      "Când terminarea programului este semnalizată printr-un semnal sonor, rotiți supapa de pe capac pentru a elibera aburul.",
      "Apăsați Anulare și desfaceți oala sub presiune după eliminarea aburului.",
      "Serviți tocănița fierbinte cu garnitură de legume.",
      "Recomandare: Dacă doriți un sos omogen și fin, mai întâi îndepărtați carnea, după care pasați legumele împreună cu supa cu ajutorul unui mixer vertical sau a unui blender.",
    ],
  },
  44: {
    title: "Risotto de ciuperci",
    time: "10 min",
    servings: "4 porții",
    ingredients: [
      "3 linguri de ulei de măsline",
      "1 ceapă, tocată mărunt",
      "1 ½ ceașcă de orez arborio",
      "2 cești de ciuperci, feliate subțire",
      "3 cești de supă de pui",
      "1 ceașcă de vin alb",
      "3 linguri de unt",
      "½ ceașcă de parmezan ras",
      "Sare Kosher",
      "piper proaspăt măcinat",
    ],
    instructions: [
      "Selectați prgramul Rumenire, turnați uleiul în vasul de gătit, adăugați și rumeniți timp de 4 minute. Adăugați orezul și ciupercile și rumeniți timp de 1 minut suplimentar. Adăugați vinul și supa, puneți capacul și blocați-l.",
      "Selectați programul Orez ( sau Gătire sub presiune, ) - Temporizator: 6 minute.",
      "După terminarea gătirii, eliberați presiunea.",
      "Deschideți oala sub presiune. Selectați programul Fierbere, adăugați untul și parmezanul. Gătiți pentru încă 3 minute, amestecând continuu.",
      "Serviți imediat.",
    ],
  },
};
