// Baza de date cu toate rețetele românești complete
const recipesData = {
  1: {
    title: "Supă cremă de roșii",
    time: "25 min",
    servings: "4 porții",
    ingredients: [
      "700g roșii",
      "1 ceapă",
      "1 ardei roșu",
      "1 morcov",
      "2 căței usturoi",
      "Busuioc proaspăt",
      "Pătrunjel",
      "Ulei de măsline",
      "Sare și piper",
    ],
    instructions: [
      "Spălați legumele și tăiați-le în bucăți mari.",
      "Selectați programul Rumenire, turnați uleiul în vasul de gătit și adăugați ceapa și usturoi. Lăsați câteva minute.",
      "Adăugați morcovul și ardeiul și gătiți încă 3 minute.",
      "Adăugați roșiile, busuiocul, sarea și piperul. Puneți capacul și blocați-l.",
      "Selectați programul Gătire sub presiune, Mică - Temporizator: 10 minute.",
      "După terminarea gătirii, eliberați presiunea. Deschideți capacul.",
      "Mixați supa până devine o cremă fină.",
      "Serviți decorată cu frunze de busuioc proaspăt.",
    ],
  },
  2: {
    title: "Ratatouille",
    time: "20 min",
    servings: "4 porții",
    ingredients: [
      "1 ceapă medie",
      "1 dovlecel zucchini",
      "1 dovlecel",
      "1 vânătă",
      "2 ardei grași",
      "400g roșii conservă",
      "3 linguri ulei de măsline",
      "Sare și piper",
      "Ierburi provensale",
    ],
    instructions: [
      "Spălați ardeii, îndepărtați cotorul, semințele și tăiați în cuburi.",
      "Îndepărtați capetele dovlecelului zucchini, ale dovlecelului și ale vinetei. Tăiați toate legumele în bucăți de dimensiuni similare.",
      "Selectați programul Rumenire, turnați uleiul în vasul de gătit, adăugați ceapa și ardeii, condimentați ușor și lăsați timp de 3 minute.",
      "Adăugați dovlecelul zucchini, dovlecelul și vânăta, și gătiți încă 5 minute.",
      "Adăugați roșiile, puneți capacul și blocați-l.",
      "Selectați programul Gătire sub presiune, Mică - Temporizator: 7 minute.",
      "După terminarea gătirii, eliberați presiunea. Deschideți capacul.",
      "Condimentați după gust.",
      "Notă: acest preparat poate fi servit cu ouă, fie prăjite sau benedict ori poate fi utilizat ca garnitură pentru carne sau pește.",
    ],
  },
  3: {
    title: "Supă cremă de praz și cartofi",
    time: "20 min",
    servings: "4 porții",
    ingredients: [
      "3 cartofi",
      "2 praji",
      "1 ceapă",
      "750ml apă sau supă de legume",
      "100ml smântână",
      "Ulei de măsline",
      "Sare și piper",
    ],
    instructions: [
      "Curățați și tăiați legumele în bucăți.",
      "Selectați programul Rumenire și adăugați uleiul.",
      "Adăugați ceapa și prazul și gătiți 5 minute.",
      "Adăugați cartofii și supa, închideți capacul.",
      "Selectați programul Gătire sub presiune - Temporizator: 10 minute.",
      "După terminare, eliberați presiunea și deschideți capacul.",
      "Mixați până obțineți o supă cremă.",
      "Adăugați smântâna și condimentați cu sare și piper.",
    ],
  },
  // Rețeta 4 - Supă cremă de dovleac - LIPSĂ detalii
  5: {
    title: "Ciorbă de cartofi",
    time: "20 min",
    servings: "4 porții",
    ingredients: [
      "200g ceapă",
      "200g morcovi",
      "150g țelină",
      "150g rădăcină de pătrunjel",
      "300g cartofi",
      "8 căței de usturoi",
      "50g ciuperci uscate – înmuiate în apă timp de 1 oră",
      "Măghiran",
      "Piper proaspăt măcinat",
      "1 linguriță de chimen",
      "4 frunze de dafin",
      "50g de slănină",
      "1,5 litri de apă",
    ],
    instructions: [
      "Tăiați ceapa în sferturi și restul legumelor în cuburi.",
      "Selectați programul Rumenire și topiți slănina.",
      "Adăugați toate legumele, chimenul și o frunză de dafin, apoi rumeniți până devin aurii.",
      "Adăugați cartofii tăiați și ciupercile înmuiate împreună cu apa în care au stat.",
      "Turnați apa și sărați.",
      "Închideți capacul și selectați programul Gătire sub presiune - Temporizator 20 minute.",
      "Adăugați măghiranul, piperul și usturoiul cu sarea.",
      "Această rețetă nu conține gluten și lactoză.",
    ],
  },
  6: {
    title: "Ciorbă de burtă",
    time: "20 min",
    servings: "4 porții",
    ingredients: [
      "400g burtă gătită",
      "40g slănină",
      "2 cepe mari",
      "2 linguri de boia dulce",
      "8 căței de usturoi",
      "Sare",
      "Piper măcinat",
      "4 frunze de dafin",
      "6 cuișoare englezești",
      "3 linguri de făină (pentru versiunea fără gluten puteți să utilizați amidon amestecat cu apă)",
      "Măghiran",
      "1,5 litri de apă",
    ],
    instructions: [
      "Puneți slănina în vasul de gătit, adăugați ceapa tocată mărunt, selectați programul Rumenire.",
      "Adăugați cartofii tăiați, piperul, cuișoarele englezești, frunzele de dafin și prăjiți.",
      "Presărați făina și turnați apa.",
      "Închideți capacul și selectați programul Gătire sub presiune - Temporizator 20 minute.",
      "Adăugați piperul, usturoiul, sarea și măghiranul.",
      "Puteți prepara o versiune fără gluten înlocuind făina cu amidon amestecat cu apă.",
    ],
  },
  7: {
    title: "Ciorbă de varză cu cârnați",
    time: "20 min",
    servings: "4 porții",
    ingredients: [
      "2 cepe",
      "400g varză murată",
      "6 frunze de dafin",
      "6 cuișoare englezești",
      "1 cartof mare",
      "2 cârnați",
      "50g slănină",
      "2 linguri de paprică dulce",
      "300g smântână acră (sau puteți utiliza smântână fără lactoză)",
      "1,5 litri de apă",
      "Sare",
    ],
    instructions: [
      "Tăiați ceapa mărunt și cârnații în semi felii.",
      "Selectați programul Rumenire, topiți slănina și adăugați ceapa și cârnații. Rumeniți până devin aurii.",
      "Adăugați paprica, cartofii tăiați și varza și toate condimentele.",
      "Turnați apa, închideți capacul și selectați programul Gătire sub presiune - temporizator: 20 minute.",
      "Adăugați sare și serviți cu smântână acră.",
    ],
  },
  8: {
    title: "Pui cu paprika",
    time: "15 min",
    servings: "4 porții",
    ingredients: [
      "4 bucăți de piept de pui",
      "3 linguri de paprica",
      "2 cepe mari",
      "3 linguri de făină (pentru o versiune fără gluten puteți utiliza amidon)",
      "1 litru de supă de pui",
      "200 ml smântână de 33% (utiliza smântână fără lactoză)",
      "50g unt (sau ulei)",
      "Sare",
    ],
    instructions: [
      "Puneți cepele tocate fin în vasul de gătit și selectați programul Rumenire. Rumeniți până devin aurii.",
      "Adăugați puiul feliat și prăjiți. Apoi adăugați piperul, făina și prăjiți în continuare.",
      "Adăugați supa și închideți capacul.",
      "Selectați programul de Gătire sub presiune - temporizator: 15 minute.",
      "Adăugați smântâna și sarea.",
      "Selectați propramul Rumenire și gătiți pentru un timp la temperatura de 120 de grade.",
    ],
  },
  9: {
    title: "Gulaș Segedin",
    time: "40 min",
    servings: "4 porții",
    ingredients: [
      "800g pulpă de porc",
      "200g ceapă",
      "300g varză murată",
      "4 frunze de dafin",
      "6 cuișoare englezești",
      "1 lingură de chimen măcinat",
      "1 lingură de praf de paprika dulce",
      "50g slănină",
      "Sare",
      "200ml smântână de 33% (utiliza smântână fără lactoză)",
      "Piper",
      "1 litru de apă",
    ],
    instructions: [
      "Tăiați carnea în bucății medii, adăugați sarea și amestecați cu piperul și chimenul. Tăiați ceapa în jumătăți.",
      "Selectați programul Rumenire, topiți slănina și adăugați ceapa și prăjiți până devin aurii.",
      "Adăugați carnea, cuișoarele englezești și frunza de dafin și prăjiți în continuare.",
      "Turnați apa și închideți capacul. Porniți Programul de Gătire sub presiune - temporizator: 30 minute.",
      "Adăugați varza și selectați programul de Gătire sub presiune - temporizator: 10 minute.",
      "Deschideți capacul, adăugați sarea și piperul. Apoi încorporați smântâna și fierbeți la 120 de grade un timp.",
    ],
  },
  10: {
    title: "Porc cu morcovi",
    time: "30 min",
    servings: "4 porții",
    ingredients: [
      "600g pulpă de porc",
      "400g morcovi",
      "1 ceapă",
      "50g slănină",
      "3 linguri de făină",
      "2 linguri de zahăr",
      "1 lămâie",
      "700ml apă",
      "Sare",
      "Nucșoară",
      "100ml smântână de 33% (sau puteți utiliza smântână fără lactoză)",
    ],
    instructions: [
      "Feliați ceapa și cartofii.",
      "Selectați programul Rumenire, topiți slănina și adăugați legumele. Rumeniți până devin aurii.",
      "Adăugați zahărul și lăsați-l să se caramelizeze. Presărați făina și continuați să prăjiți.",
      "Apoi adăugați carnea tăiată și sarea, continuați să prăjiți.",
      "Turnați apa, închideți capacul și selectați programul Gătire sub presiune - temporizator: 30 minute.",
      "Adăugați sarea, coaja de lămâie și sucul de lămâie împreună cu nucșoara. Încorporați smântâna.",
    ],
  },
  11: {
    title: "Vită în sos de mărar",
    time: "70 min",
    servings: "4 porții",
    ingredients: [
      "600g ceafă de vită",
      "100g ceapă",
      "4 linguri de făină (pentru o versiune fără gluten puteți utiliza amidon)",
      "80g unt (sau puteți utiliza ulei)",
      "200ml smântână de 33% (o puteți înlocui cu smântână fără lactoză)",
      "1 legătură de mărar",
      "2 lămâi",
      "3-4 linguri de zahăr",
      "Sare",
      "4 frunze de dafin",
      "6 cuișoare englezești",
      "8 boabe de piper",
      "1,5 litri de apă",
    ],
    instructions: [
      "Tăiați ceafa de vită în cuburi mari și puneți-le în vasul de gătit. Adăugați condimentele, sarea, ceapa și turnați apa.",
      "Închideți capacul și selectați programul Gătire sub presiune - temporizator: 60 minute.",
      "Mutați supa într-un bol și îndepărtați condimentele.",
      "Selectați programul Rumenire și gătiți făina cu untul. Turnați supa la loc în vasul de gătit împreună cu carnea și continuați să gătiți timp de 10 minute suplimentare.",
      "Adăugați sarea, sucul de lămâie, mărarul tocat și smântâna.",
      "Pentru o versiune fără gluten puteți utiliza făină fără gluten. De asemenea, puteți utiliza produse fără lactoză.",
    ],
  },
  12: {
    title: "Piftie",
    time: "55 min",
    servings: "8 porții",
    ingredients: [
      "1kg rasol de porc",
      "3L apă",
      "1 lingură sare",
      "6 căței de usturoi",
      "2 morcovi",
      "2 cepe",
      "1 țelină",
      "3 frunze de dafin",
      "1 rădăcină pătrunjel",
      "Piper boabe",
    ],
    instructions: [
      "Puneți rasolul de porc în oală, împreună cu apa.",
      "Selectați programul Gătire sub presiune și setați timpul la 30 minute. Închideți capacul și apăsați Start.",
      "După semnalul sonor, apăsați butonul de pe capac și eliberați aburul. Apăsați Anulare și deschideți capacul.",
      "Adăugați legumele întregi.",
      "Selectați programul Gătire sub presiune și setați timpul la 15 minute. Închideți capacul și apăsați Start.",
      "După semnalul sonor, apăsați butonul de pe capac și eliberați aburul. Apăsați Anulare și deschideți capacul.",
      "Selectați programul Fierbere la foc mic și setați timpul la 10 minute. Închideți capacul și apăsați Start.",
      "După semnalul sonor, apăsați butonul de pe capac și eliberați aburul. Apăsați Anulare și deschideți capacul.",
      "Îndepărtați carnea de pe oase, scoateți legumele și strecurați supa pentru o piftie clară.",
      "Pregătiți bolurile pentru piftie cu rondele din morcovul fiert, frunze de pătrunjel și carnea de porc.",
      "Mutați supa în boluri, iar când aceasta s-a răcit, le puteți pune la frigider.",
    ],
  },
  13: {
    title: "Gulaș de vită",
    time: "50 min",
    servings: "4 porții",
    ingredients: [
      "800g pulpă de vită",
      "30g slănină",
      "300g ceapă",
      "4 frunze de dafin",
      "1 linguriță de chimen",
      "1 ardei iute",
      "6 cuișoare englezești",
      "2 linguri de paprica dulce",
      "30g piure de roșii",
      "1 cartof mediu",
      "8 căței de usturoi",
      "Sare",
      "Măghiran",
      "Piper",
      "1,5 litri de apă",
    ],
    instructions: [
      "Tăiați carnea de vită în cuburi mari, sărați și amestecați-o într-un bol cu paprica.",
      "Tăiați ceapa mărunt și puneți-o în vasul de gătit. Selectați programul Rumenire și apăsați Start.",
      "Rumeniți slănina cu frunza de dafin, chimenul și cuișoarele englezești. Adăugați piureul de roșii și continuați să gătiți, după care adăugați carnea, ardeiul iute și lăsați la rumenit.",
      "Turnați apa, închideți capacul și selectați programul Gătire sub presiune - temporizator: 40 minute.",
      "Adăugați cartoful tăiat mărunt și condimentați cu usturoi, sare, piper și măghiran.",
      "Selectați programul Rumenire și gătiți la 120 de grade aproximativ 10 minute.",
      "Această rețetă nu conține gluten și lactoză.",
    ],
  },
  14: {
    title: "Tocăniță de vițel",
    time: "25 min",
    servings: "4 porții",
    ingredients: [
      "600 g carne de vițel",
      "2 cepe sau 400 g",
      "4 morcovi sau 250 g",
      "1 ardei roșu sau 250 g",
      "1 ardei verde sau 250 g",
      "2 căței de usturoi",
      "200 g sos de roșii",
      "20 ml vin roșu",
      "2 linguri de ulei de măsline",
      "Sare și piper",
    ],
    instructions: [
      "Puneți 2 linguri de ulei în vasul de gătit. Selectați programul Rumenire și apăsați Start.",
      "După semnalul sonor, adăugați usturoiul tocat, ceapa și ardeiul feliat. Lăsați la înăbușit timp de 5 minute. Când legumele sunt pătrunse, apăsați Anulare.",
      "Adăugați carnea (tăiată în bucățele mici), morcovii feliați, vinul roșu și sosul de roșii.",
      "Condimentați cu sare și piper.",
      "Închideți capacul și selectați programul de Gătire sub presiune și setați temporizatorul pentru 20 minute. Apăsați Start.",
      "Când terminarea programului este semnalizată printr-un semnal sonor, rotiți supapa de pe capac pentru a elibera aburul.",
      "Apăsați Anulare și desfaceți oala sub presiune după eliminarea aburului.",
      "Serviți tocănița fierbinte cu garnitură de legume.",
      "Recomandare: Dacă doriți un sos omogen și fin, mai întâi îndepărtați carnea, după care pasați legumele împreună cu supa cu ajutorul unui mixer vertical sau a unui blender.",
    ],
  },
  15: {
    title: "Fabada asturiana",
    time: "35 min",
    servings: "4 porții",
    ingredients: [
      "600 g fasole boabe",
      "200 g ceapă sau 1 ceapă medie",
      "1 roșie",
      "100 g ardei verde",
      "2 căței de usturoi",
      "160 g șuncă",
      "160 g chorizo",
      "160 g caltaboș",
      "60 ml apă",
    ],
    instructions: [
      "Lăsați la înmuiat boabele de fasole în apă din belșug timp de 8 ore.",
      "Adăugați în vasul de gătit: ceapa (tăiată în sferturi), roșia (curățată de coajă și tocată), 2 căței de usturoi (mărunțiți), ardeiul verde (feliat) și fasolea înmuiată.",
      "Adăugați șunca, chorizo-ul și caltaboșul și acoperiți cu apă.",
      "Selectați programul de Gătire sub presiune, Mod mare, setați temporizatorul pe 35 minute și apăsați Start.",
      "Când auziți semnalul sonor, rotiți supapa de pe capac pentru a elibera aburul.",
      "Apăsați Anulare și desfaceți oala sub presiune după eliminarea aburului.",
      "Îndepărtați caltaboșul, chorizo-ul și șunca, și tăiați-le în bucăți medi.",
      "Turnați boabele de fasole într-un bol de supă sau în farfurii individuale și acoperiți cu carnea tăiată.",
      "Recomandare: Dacă doriți o supă mai densă, îndepărtați o cantitate din lichid, mixați-o cu două linguri de fasole, după care readăugați-o la tocăniță.",
    ],
  },
  16: {
    title: "Midii a la marinera",
    time: "10 min",
    servings: "4 porții",
    ingredients: [
      "1 kg midii",
      "100 g ceapă",
      "2 căței de usturoi",
      "100 g ardei roșu",
      "10 g paprică",
      "2 frunze de dafin",
      "10 g pătrunjel",
      "20 ml vin alb",
      "2 linguri de ulei de măsline",
      "Sare și piper",
    ],
    instructions: [
      "Curățați midiile, îndepărtând firele și frecând scoica cu un burete abraziv pentru a îndepărta toate impuritățile.",
      "Curățați și tocați usturoiul, ceapa și piperul.",
      "Turnați 2 linguri de ulei în vasul de gătit. Selectați programul Rumenire și apăsați Start.",
      "Când mașina emite un semnal sonor, adăugați legumele tocate. Rumeniți ușor timp de 5 minute sau până când sunt pătrunse.",
      "Adăugați midiile curățate, frunzele de dafin, vinul alb și paprica.",
      "Închideți capacul și selectați programul de Gătire sub presiune și setați temporizatorul pentru 5 minute. Apăsați Start.",
      "Când terminarea programului este semnalizată printr-un semnal sonor, rotiți supapa de pe capac pentru a elibera aburul.",
      "Apăsați Anulare și desfaceți oala sub presiune după eliminarea aburului.",
      "Scoateți midiile și amplasați-le într-un vas. Acoperiți-le cu supa rezultată în urma gătitului.",
      "Presărați deasupra pătrunjel proaspăt tocat chiar înainte de servire.",
      "Recomandare: Pentru o aromă mai condimentată, adăugați paprică iute în loc de dulce sau un vârf de praf de ardei iute.",
    ],
  },
  17: {
    title: "Varză călită cu afumătură",
    time: "30 min",
    servings: "6 porții",
    ingredients: [
      "1 varză dulce medie, tocată fideluță",
      "2 cepe, tocate mărunt",
      "2 căței de usturoi, tocați mărunt",
      "1 ardei capia, tocat cubulețe",
      "300g afumătură",
      "150ml pastă de tomate",
      "3 linguri de ulei",
      "2 foi de dafin",
      "Cimbru",
      "1 lingură boia dulce",
      "300ml apă",
      "Sare și piper după gust",
    ],
    instructions: [
      "Puneți uleiul în oală.",
      "Selectați programul Rumenire și apăsați Start.",
      "După semnalul sonor, căliți ceapa și afumatura timp de 10 minute. După semnalul sonor, apăsați Anulare.",
      "Adăugați restul de ingrediente rămase.",
      "Selectați programul Gătire sub presiune și setați timpul la 20 minute. Închideți capacul și apăsați Start.",
      "După semnalul sonor, apăsați butonul de pe capac și eliberați aburul. Apăsați Anulare și deschideți capacul.",
      "Serviți alături de mămăligă caldă și ardei iute.",
    ],
  },
  18: {
    title: "Cod cu scoici",
    time: "10 min",
    servings: "4 porții",
    ingredients: [
      "600 g cod",
      "200 g scoici",
      "100 g ceapă sau ½ ceapă",
      "100 g praz",
      "2 căței de usturoi",
      "10 g pătrunjel",
      "20 ml vin alb",
      "2 linguri de ulei de măsline",
      "Sare și piper",
    ],
    instructions: [
      "Curățați și tocați usturoiul, ceapa și prazul.",
      "Turnați 2 linguri de ulei în vasul de gătit. Selectați programul Rumenire și apăsați Start.",
      "Când mașina emite un semnal sonor, adăugați usturoiul tocat, ceapa și prazul.",
      "Apăsați Start. Amestecați timp de 5 minute sau până când sunt gătite. Apăsați Anulare.",
      "Adăugați scoicile (curățate), vinul alb și bucățile de pește (condimentate).",
      "Închideți capacul și selectați programul de Gătire sub presiune, și setați temporizatorul pentru 5 minute. Apăsați Start.",
      "Când terminarea programului este semnalizată printr-un semnal sonor, rotiți supapa de pe capac pentru a elibera aburul.",
      "Apăsați Anulare și desfaceți oala sub presiune după eliminarea aburului.",
      "Serviți bucățile de pește cu scoicile desfăcute deasupra codului.",
      "Adăugați condimente suplimentare, dacă este nevoie, și presărați pătrunjel proaspăt tocat.",
      "Recomandare: Dacă nu doriți să utilizați vin, puteți să-l înlocuiți cu supă de pește. Această rețetă poate fi utilizată și cu alte tipuri de pește alb.",
    ],
  },
  19: {
    title: "Sepie cu cartofi",
    time: "15 min",
    servings: "4 porții",
    ingredients: [
      "800 g sepie",
      "100 g ceapă sau ½ ceapă",
      "400 g cartofi",
      "100 g ardei verde",
      "2 căței de usturoi",
      "10 g pătrunjel",
      "30 ml apă",
      "8 fire de șofran",
      "2 linguri de ulei de măsline",
      "Sare și piper",
    ],
    instructions: [
      "Decojiți și mărunțiți cățeii de usturoi, ceapa și ardeiul.",
      "Curățați sepia și tăiați-o în bucăți mici.",
      "Turnați 2 linguri de ulei în vasul de gătit. Selectați programul Rumenire și apăsați Start.",
      "După semnalul sonor, adăugați usturoiul tocat, ceapa și ardeiul împreună cu șofranul.",
      "Amestecați din când în când astfel încât ingredientele să fie gătite uniform, aproximativ 5 minute.",
      "După terminare, apăsați Anulare.",
      "Adăugați bucățile de sepie și cartofii (curățați de coajă și feliați). Acoperiți cu apă și sărați.",
      "Închideți capacul și selectați programul de Gătire sub presiune și setați temporizatorul pentru 10 minute. Apăsați Start.",
      "Când terminarea programului este semnalizată printr-un semnal sonor, rotiți supapa de pe capac pentru a elibera aburul.",
      "Apăsați Anulare și desfaceți oala sub presiune după eliminarea aburului.",
      "Serviți sepia cu cartofi și presărați cu pătrunjelul tocat în ultimul moment.",
      "Recomandare: Această rețetă poate fi utilizată și cu inele de calamar în loc de sepie. Adăugați un praf de paprica sau șofran dacă doriți să fie mai condimentat.",
    ],
  },
  20: {
    title: "Budincă de ciocolată fără făină",
    time: "7 min",
    servings: "4 porții",
    ingredients: [
      "115 g ciocolată semi-dulce, ruptă în bucățele",
      "3 linguri de unt, plus unt suplimentar pentru ungerea formelor",
      "2 ouă",
      "¼ ceașcă de zahăr pudră",
      "2 linguri cacao neîndulcită",
      "2 lingurițe de extract de vanilie",
    ],
    instructions: [
      "Într-un bol, topiți ciocolata și untul, apoi lăsați-le la răcit.",
      "Bateți ouăle, zahărul și extractul de vanilie până când devin spumoase.",
      "Adăugați amestecul de ciocolată peste ouă, apoi adăugați cacaua și amestecați folosind un mixer. Amestecați până totul este bine încorporat.",
      "Umpleți formele unse cu unt pe jumătate.",
      "Turnați 1 ¼ ceașcă de apă în vasul de gătit și amplasați suportul metalic în vas.",
      "Amplasați formele (numărul depinde de dimensiunile acestora) pe suportul metalic.",
      "Selectați programul de Gătire sub presiune, Mare - Temporizator: 7 minute.",
      "După terminarea gătirii, eliberați presiunea. Deschideți capacul.",
      "Serviți cu frișcă sau cu înghețată de vanilie.",
    ],
  },
  21: {
    title: "Dulceață de piersici",
    time: "30 min",
    servings: "4 borcane",
    ingredients: [
      "1kg piersici, fără sâmburi și tocate cuburi",
      "150g zahăr",
      "Sucul de la 1 lămâie",
      "Esență de vanilie",
      "50ml apă",
    ],
    instructions: [
      "Adăugați toate ingredientele în oală.",
      "Selectați programul Gătire sub presiune. Apăsați săgeata în jos și setați presiunea la Medie. Setați timpul la 10 minute. Închideți capacul și apăsați Start.",
      "După semnalul sonor, apăsați butonul de pe capac și eliberați aburul. Apăsați Anulare și deschideți capacul.",
      "Selectați programul Fierbere la foc mic și setați timpul la 15 minute. Închideți capacul și apăsați Start.",
      "După semnalul sonor, apăsați butonul de pe capac și eliberați aburul.",
      "Dacă dulceața este prea lichidă, selectați programul Rumenire pentru încă 10 minute.",
      "Turnați dulceața în borcane sterilizate și lăsați să se răcească.",
    ],
  },
  22: {
    title: "Cheesecake",
    time: "27 min",
    servings: "6 porții",
    ingredients: [
      "4 biscuiți cu graham întregi, zdrobiți",
      "2 lingur de unt, topit",
      "230 g brânză topită",
      "½ ceașcă de zahăr",
      "2 ouă, bătute ușor",
      "½ ceașcă de smântână acră",
    ],
    instructions: [
      "Într-un bol, amestecați biscuiții zdrobiți și untul. Împărțiți amestecul astfel obținut, egal între forme și apăsați amestecul pe fundul formelor.",
      "Puneți formele în vasul de gătit. Selectați programul de Coacere la 175 °C Temporizator: 10 minute. Lăsați la răcit.",
      "Combinați toate ingredientele rămase într-un al doilea bol până când sunt omogene, apoi turnați amestecul în formele preparate.",
      "Acoperiți fiecare formă cu folie de plastic sau de aluminiu.",
      "Trunați 1 ceașcă de apă în vasul de gătit și amplasați suportul metalic în vas.",
      "Amplasați formele (numărul depinde de dimensiunile acestora) pe suportul metalic.",
      "Selectați programul de Gătire sub presiune, Mică - Temporizator: 17 minute.",
      "După terminarea gătirii, eliberați presiunea. Deschideți capacul.",
      "Lăsați să se răcească înainte de a le servi.",
    ],
  },
  23: {
    title: "Pulpe de miel înăbușite",
    time: "25-30 min",
    servings: "4-6 porții",
    ingredients: [
      "2 roșii tocate",
      "6 pulpe de miel decupate în stil francez",
      "¼ ceașcă de făină simplă, cu un vârf generos de sare și piper",
      "2 linguri de ulei de măsline",
      "1 ceapă, tocată",
      "3 morcovi, feliați gros",
      "1 cățel de usturoi, decojit",
      "1 lingură de oregano proaspăt tocat",
      "Coajă rasă de la 1 lămâie",
      "¾ ceașcă de vin roșu",
      "¼ ceașcă de supă de vită sau de legume",
      "Sare și piper proaspăt măcinat",
      "Pentru un sos mai gros: 1 lingură de făină simplă amestecată cu 2 linguri de apă rece (opțional)",
    ],
    instructions: [
      "Ștergeți pulpele cu o cârpă uscată, ușor umezită, apoi dați-le prin făina condimentată, scuturând excesul.",
      "Selectați programul Rumenire. Încălziți jumătate din cantitatea de ulei în vasul de gătit și rumeniți pulpele câte două o dată. Îndepărtați și lăsați deoparte.",
      "Adăugați uleiul rămas cu ceapa, morcovul și usturoiul în vasul de gătit și rumeniți timp de 5 minute, amestecând ocazional.",
      "Adăugați roșiile, oregano, coaja de lămâie, vinul, supa și lăsați să fiarbă, amestecând bine câteva minute.",
      "Repuneți pulpele înapoi în vasul de gătit și condimentați bine. Cu ajutorul unei linguri, turnați puțin sos și legume peste pulpe.",
      "Închideți capacul și blocați-l. Selectați programul de Gătire sub presiune, Mare - Temporizator: 20-25 minute (în funcție de grosimea pulpelor).",
      "Eliberați presiunea și deschideți capacul.",
      "Îndepărtați cu grijă pulpele de miel din vasul de gătit - carnea ar trebui să fie foarte fragedă, aproape să se desprindă de os.",
      "Dacă doriți ca sosul să fie mai gros, selectați programul Fierbere și amestecați făina și apa câte puțin până la îngroșare.",
    ],
  },
  24: {
    title: "Risotto de ciuperci",
    time: "10 min",
    servings: "4 porții",
    ingredients: [
      "3 linguri de ulei de măsline",
      "1 ceapă, tocată mărunt",
      "1 ½ ceașcă de orez arborio",
      "2 cești de ciuperci, feliate subțire",
      "3 cești de supă de pui",
      "1 ceașcă de vin alb",
      "3 linguri de unt",
      "½ ceașcă de parmezan ras",
      "Sare Kosher",
      "Piper proaspăt măcinat",
    ],
    instructions: [
      "Selectați prgramul Rumenire, turnați uleiul în vasul de gătit, adăugați și rumeniți timp de 4 minute.",
      "Adăugați orezul și ciupercile și rumeniți timp de 1 minut suplimentar.",
      "Adăugați vinul și supa, puneți capacul și blocați-l.",
      "Selectați programul Orez (sau Gătire sub presiune) - Temporizator: 6 minute.",
      "După terminarea gătirii, eliberați presiunea.",
      "Deschideți oala sub presiune. Selectați programul Fierbere, adăugați untul și parmezanul.",
      "Gătiți pentru încă 3 minute, amestecând continuu.",
      "Serviți imediat.",
    ],
  },
  25: {
    title: "Risotto de dovleac",
    time: "10 min",
    servings: "4 porții",
    ingredients: [
      "3 cești de dovleac",
      "1 ½ ceașcă de orez arborio",
      "1 lingură de unt",
      "2 linguri de ulei de măsline",
      "1 ceapă mică, tocată mărunt",
      "½ ceașcă de vin alb sec",
      "3 ½ cești de supă de pui sau de legume",
      "1 linguriță de frunze de salvie",
      "Sare Kosher",
      "Piper negru proaspăt măcinat",
      "3 linguri de parmezan proaspăt ras",
      "2 linguri de pătrunjel proaspăt tocat",
    ],
    instructions: [
      "Curățați dovleacul de coajă și de semințe, și tăiați-l în cuburi de 1 cm.",
      "Selectați programul Rumenire. Încălziți untul și uleiul în vasul de gătit și adăugați dovleacul și gătiți pentru 3 minute.",
      "Adăugați orezul și amestecați pentru a combina cu dovleacul.",
      "Adăugați vinul și amestecați timp de 1 minut.",
      "Adăugați supa, condimentați ușor, închideți capacul și blocați-l.",
      "Selectați programul Orez (sau Gătire sub presiune,) - Temporizator: 6 minute.",
      "După terminarea gătirii, eliberați presiunea.",
      "Deschideți capacul și amestecați salvia.",
      "Selectați programul Fierbere timp de 4 minute, amestecând continuu până când orezul devine fraged, gros și cremos.",
      "Încorporați parmezanul și condimentați după gust.",
      "Serviți imediat cu pătrunjel presărat deasupra.",
    ],
  },
  26: {
    title: "Budincă de ovăz cu ananas și mentă",
    time: "5 min",
    servings: "4 porții",
    ingredients: [
      "2 cești de ovăz prefiert sau ovăz clasic",
      "2 ½ cești de apă",
      "3 linguri de zahăr",
      "½ linguriță de scorțișoară",
      "Un vârf de sare",
      "⅓ ceașcă de lapte",
      "1 ceașcă de ananas tăiat în bucăți",
      "2 linguri de mentă proaspătă",
    ],
    instructions: [
      "Pregătiți toate ingredientele. Amestecați ovăzul, zahărul, scorțișoara, sarea și apa în vasul de gătit.",
      "Închideți capacul și supapa de presiune.",
      "Selectați programul Budincă - Temporizator: 5 minute.",
      "Când budinca este gata, eliberați presiunea înainte de a deschide capacul.",
      "Deschideți capacul, adăugați laptele și amestecați bine.",
      "Turnați budinca în 4 boluri și presărați ananasul și menta deasupra.",
    ],
  },
  27: {
    title: "Bundică de ovăz",
    time: "20 min",
    servings: "4 porții",
    ingredients: ["½ ceașcă de ovăz", "2 cești de apă", "Un vârf de sare"],
    instructions: [
      "Combinați ingredientele în vasul de gătit. Închideți capacul și supapa de presiune.",
      "Selectați programul Budincă și creșteți durata la 15 minute.",
      "Când Budincă este gata, lăsați-o să se răcească (fără a elibera presiunea) timp de 10 minute.",
      "După această durată, desfaceți supapa de presiune și eliberați aburul.",
      "Deschideți capacul, amestecați ovăzul și lăsați să stea 5 minute ca să absoarbă apa.",
      "Sfat: turnați deasupra lapte proaspăt, fructe proaspete sau uscate, nuci mărunțite sau granola, și îndulcitorul dumneavoastră preferat - zahăr brun sau alb, sirop de arțar sau de agave.",
    ],
  },
  28: {
    title: "Humus",
    time: "30 min",
    servings: "4 porții",
    ingredients: [
      "1 ceașcă de boabe de năut lăsată la înmuiat timp de minim 12 ore",
      "1 lămâie întreagă, stoarsă",
      "1 linguriță de tahini",
      "1 linguriță de chimen măcinat",
      "4 cești de apă pentru a găti boabele",
      "Sare Kosher",
      "Piper negru proaspăt măcinat",
    ],
    instructions: [
      "Lăsați boabele de năut la înmuiat peste noapte.",
      "Puneți năutul scurs în vasul de gătit cu 4 cești de apă.",
      "Selectați programul Tocană/Supă, (sau Gătire sub presiune, Ridicată) - Temporizator: 30 minute (în funcție de tipul și de dimensiunea boabelor).",
      "După terminarea gătirii, eliberați presiunea. Deschideți capacul.",
      "Scurgeți boabele și puneți-le deoparte, păstrați 1 ½ ceașcă din lichidul obținut în urma fierberii.",
      "Puneți boabele într-un bol separat, și și pasați-le cu ajutorul unui mixer vertical.",
      "Adăugați sucul de lămâie, tahini și chimenul. Amestecați până la omogeneizare.",
      "Adăugați treptat lichidul păstrat în urma fierberii, până obțineți consistența dorită.",
      "Condimentați după gust.",
      "Serviți humusul cu pită și legume curățate de coajă (castraveți, morcovi, țelină sau gogoșari) tăiate în felii.",
    ],
  },
  29: {
    title: "Ciorbă de vită",
    time: "34 min",
    servings: "6 porții",
    ingredients: [
      "500g carne de vită, tăiată cuburi",
      "3 linguri ulei",
      "2 cepe, tocate mărunt",
      "3 cartofi mici, tăiați cuburi",
      "1 morcov, tăiat rondele",
      "1 ardei gras",
      "1 rădăcină țelină",
      "400ml suc de roșii",
      "3 foi de dafin",
      "1 păstârnac, tocat",
      "100g mazăre",
      "100g păstăi",
      "1 lingură cimbru uscat",
      "1,5L apă",
      "Sare și piper",
    ],
    instructions: [
      "Puneți uleiul în oală.",
      "Selectați Rumenire și apăsați Start.",
      "După semnalul sonor, adăugați ceapa și gătiți 5 minute.",
      "Adăugați carnea și gătiți încă 5 minute. După terminare, apăsați Anulare.",
      "Adăugați toate celelalte ingrediente și 300ml apă.",
      "Selectați Gătire sub presiune. Setați timpul la 15 minute. Închideți capacul și apăsați Start.",
      "După semnalul sonor, deschideți supapa și eliberați aburul. Apăsați Anulare și deschideți capacul.",
      "Adăugați apa rămasă, cimbrul, sarea și piperul.",
      "Selectați Tocană/Supă. Setați timpul la 9 minute. Închideți capacul și apăsați Start.",
      "După semnalul sonor, deschideți supapa și eliberați aburul. Apăsați Anulare și deschideți capacul.",
    ],
  },
  30: {
    title: "Pulpe de pui la grătar",
    time: "15 min",
    servings: "4 porții",
    ingredients: [
      "1 lingură ulei de măsline",
      "8 pulpe de pui",
      "2 căței usturoi, decojiți și tocați",
      "1 ceapă medie, mărunțită",
      "⅔ ceașcă sos barbecue",
      "⅔ ceașcă sos chili",
      "Sare și piper",
    ],
    instructions: [
      "Selectați programul Rumenire. Încălziți uleiul și prăjiți pulpele de pui timp de aproximativ 6 minute.",
      "Adăugați usturoiul și ceapa. Selectați programul Rumenire - Temporizator: 3 minute.",
      "Adăugați ingredientele rămase și amestecați.",
      "Selectați programul de Gătire sub presiune, Mare - Temporizator: 15 minute.",
      "După terminarea gătirii, eliberați presiunea. Deschideți capacul.",
      "Condimentați cu sare și piper. Serviți.",
    ],
  },
  31: {
    title: "Sos bolognese de carne de vită",
    time: "10 min",
    servings: "4 porții",
    ingredients: [
      "½ lingură ulei de măsline",
      "3 bucăți șuncă",
      "2 cepe medii, tocate",
      "2 căței usturoi, zdrobiți",
      "500g carne tocată de vită",
      "500g carne tocată de porc",
      "1 morcov, tăiat cubulețe",
      "1 rădăcină țelină, tăiată cubulețe",
      "½ ceașcă vin roșu",
      "230g pastă de roșii",
      "800g roșii zdrobite din conservă, scurse de zeamă",
      "2 lingurițe oregano uscat",
      "2 lingurițe busuioc uscat",
      "Sare și piper după gust",
      "½ ceașcă parmezan ras",
      "2 frunze dafin",
    ],
    instructions: [
      "Selectați programul Rumenire. Încălziți uleiul împreună cu carnea de vită, de porc, șunca, ceapa, morcovul, țelina și usturoiul până când carnea este rumenită.",
      "Desfaceți carnea gătită cu ajutorul unei spatule, după care adăugați ingredientele rămase și amestecați bine.",
      "Selectați programul de Gătire sub presiune, Mare - Temporizator: 10 minute.",
      "După terminarea gătirii, eliberați presiunea. Deschideți capacul.",
      "Condimentați după gust, îndepărtați frunzele de dafin. Serviți împreună cu parmezan suplimentar.",
    ],
  },
  32: {
    title: "Chili con Carne",
    time: "10 min",
    servings: "4 porții",
    ingredients: [
      "1kg carne tocată de vită degresată",
      "2 cepe tăiate cubulețe mici",
      "2 căței usturoi, decojiți și tocați mărunt",
      "2 linguri ulei de măsline",
      "1 linguriță chimen măcinat",
      "800g roșii bucăți din conservă, scurse",
      "230g pastă de roșii",
      "2 conserve de 425g fasole roșie, clătită și scursă",
      "2 linguri praf de ardei iute",
      "½ linguriță ardei iute Ancho",
      "¼ linguriță ardei iute pudră Cayenne",
      "Sare Kosher",
      "Piper negru proaspăt măcinat",
    ],
    instructions: [
      "Selectați programul Rumenire. Prăjiți ușor carnea de vită în ulei. Condimentați cu puțină sare și piper.",
      "Adăugați ceapa, usturoiul, chimenul, praful de ardei iute, praful de ardei iute Ancho și de Cayenne. Amestecați bine.",
      "Adăugați roșiile, sosul de roșii și fasolea. Amestecați din nou și închideți capacul. Selectați programul de Gătire sub presiune, Mică Temporizator: 10 minute.",
      "După terminarea gătirii, eliberați presiunea. Deschideți capacul. Serviți.",
      "Notă: Ca preparatul să aibă un gust mai picant, puteți adăuga câteva picături de Tabasco înainte de a-l servi. Chili con carne poate fi servit singur sau împreună cu orez.",
    ],
  },
  33: {
    title: "Gulaș de vită",
    time: "25 min",
    servings: "4 porții",
    ingredients: [
      "700g carne de vită, tăiată cuburi",
      "3 linguri ulei",
      "2 cepe, tocate mărunt",
      "4 cartofi mici, tăiați cuburi",
      "2 morcovi, tăiați rondele",
      "3 căței usturoi",
      "1 lingură chimen",
      "1 lingură boia",
      "2 foi dafin",
      "1 ardei gras verde",
      "2 linguri măghiran",
      "400g roșii decojite/pastă de roșii",
      "½ cană vin roșu",
      "½ cană apă",
      "Ardei iute pentru servit",
    ],
    instructions: [
      "Puneți uleiul în oală.",
      "Selectați Rumenire și apăsați Start.",
      "După semnalul sonor, adăugați ceapa și gătiți 5 minute.",
      "Adăugați carnea, boiaua, măghiranul și gătiți încă 5 minute. După terminare, apăsați Anulare.",
      "Adăugați restul de ingrediente.",
      "Selectați Gătire sub presiune. Setați timpul la 15 minute. Închideți capacul și apăsați Start.",
      "După semnalul sonor, deschideți supapa și eliberați aburul. Apăsați Anulare și deschideți capacul.",
    ],
  },
  34: {
    title: "Vită Stroganoff",
    time: "30 min",
    servings: "4 porții",
    ingredients: [
      "700g carne de vită, tăiată cuburi",
      "2 cepe, tocate julien",
      "250g ciuperci, tăiate felii",
      "10g făină",
      "1 lingură muștar",
      "125g smântână",
      "50ml ulei",
      "20g unt",
      "3 castraveți murați, tăiați rondele",
      "1 cană vin alb",
      "Sare și piper după gust",
    ],
    instructions: [
      "Puneți uleiul în oală.",
      "Selectați Rumenire și apăsați Start.",
      "După semnalul sonor, adăugați ceapa și gătiți 5 minute.",
      "Adăugați carnea și făina (opțional) și gătiți încă 5 minute. După terminare, apăsați Anulare. Adăugați restul de ingrediente.",
      "Selectați Gătire sub presiune. Setați timpul la 15 minute. Închideți capacul și apăsați Start.",
      "După semnalul sonor, deschideți supapa și eliberați aburul. Apăsați Anulare și deschideți capacul.",
    ],
  },
  35: {
    title: "Fasole cu ciolan afumat",
    time: "40 min",
    servings: "6 porții",
    ingredients: [
      "700g ciolan afumat, tăiat felii",
      "500g fasole boabe uscată",
      "2 cepe, tocate mărunt",
      "2 morcovi, tăiați rondele",
      "500ml pastă de roșii",
      "3 linguri ulei",
      "2 foi dafin",
      "Cimbru",
      "1 lingură boia dulce",
      "1 linguriță seminț de chimen",
      "Sare și piper după gust",
    ],
    instructions: [
      "Puneți în oală fasolea spălată și 1,5L apă.",
      "Selectați Gătire sub presiune și setați timpul la 20 minute. Închideți capacul și apăsați Start.",
      "După semnalul sonor, deschideți supapa și eliberați aburul. Apăsați Anulare și deschideți capacul.",
      "Scoateți fasolea și aruncați apă.",
      "Selectați Rumenire. După semnalul sonor, adăugați ceapa și ciolanul afumat și gătiți timp de 5 minute.",
      "Adăugați ciolanul afumat și gătiți pentru încă 5 minute. După semnalul sonor, apăsați Anulare.",
      "Adăugați restul de ingrediente, inclusiv fasolea fiartă.",
      "Selectați Gătire sub presiune și setați timpul la 10 minute. Închideți capacul și apăsați Start.",
      "După semnalul sonor, deschideți supapa și eliberați aburul. Apăsați Anulare și deschideți capacul.",
    ],
  },
  36: {
    title: "Sarmale",
    time: "40 min",
    servings: "25 bucăți",
    ingredients: [
      "500g carne de porc tocată",
      "100g orez",
      "3 linguri ulei",
      "2 cepe roșii",
      "1 lingură pastă de roșii",
      "500ml suc de roșii",
      "2 verze murate",
      "Piper boabe",
      "2 foi dafin",
      "1 linguriță cimbru",
      "½ linguriță măghiran",
      "1 linguriță boia dulce",
      "Sare și piper după gust",
      "Afumatură",
      "Ardei iute și mămăligă pentru servit",
    ],
    instructions: [
      "Puneți uleiul în oală.",
      "Selectați Rumenire și apăsați Start.",
      "După semnalul sonor, adăugați ceapa și căliți timp de 5 minute.",
      "Adăugați orezul, 1 cană apă, sarea și condimentele și gătiți încă 5 minute. După terminare, apăsați Anulare.",
      "Turnați sosul obținut peste carnea tocată, adăugați cimbru, sare și piper (dacă este nevoie) și amestecați bine.",
      "Tăiați varza murată fideluță și puneți-o pe fundul oalei. Împachetați sarmalele și puneți-le în oală.",
      "Acoperiți sarmalele cu varza murată tocată și afumătura tăiată feliuțe. Puneți foile de dafin, boabele de piper, sucul de roșii și 1 cană apă.",
      "Selectați Gătire sub presiune și setați timpul la 30 minute. Închideți capacul și apăsați Start.",
      "După semnalul sonor, deschideți supapa și eliberați aburul. Apăsați Anulare și deschideți capacul.",
      "Serviți alături de ardei iute și mămăligă.",
    ],
  },
  37: {
    title: "Papricaș de pui",
    time: "35 min",
    servings: "6 porții",
    ingredients: [
      "800g carne de pui",
      "3 linguri ulei",
      "4 cepe, tocate mărunt",
      "2 ardei capia, tocați mărunt",
      "3 căței usturoi, tocați",
      "250ml apă",
      "2 roșii",
      "2 foi dafin",
      "2 linguri făină (opțional)",
      "1 lingură boia dulce",
      "Sare și piper după gust",
      "Pătrunjel",
      "Pentru găluște: 2 ouă, 200g făină, 2 linguri ulei, sare",
    ],
    instructions: [
      "Pentru găluște: Selectați Fierbere la foc mic. Setați timpul la 10 minute.",
      "Turnați 1,5L apă în oală. Formați cu o linguriță găluștele și puneți una câte una în oală.",
      "Închideți capacul și apăsați Start.",
      "După semnalul sonor, deschideți supapa și eliberați aburul. Apăsați Anulare și deschideți capacul.",
      "Scoateți găluștele și mențineți-le calde. Aruncați apa.",
      "Pentru papricaș: Selectați Rumenire și apăsați Start. După semnalul sonor, adăugați ceapa și căliți timp de 5 minute.",
      "Adăugați carnea și făina (opțional), gătiți pentru încă 5 minute. După semnalul sonor, apăsați Anulare. Adăugați restul de ingrediente.",
      "Selectați Gătire sub presiune și setați timpul la 15 minute. Închideți capacul și apăsați Start.",
      "După semnalul sonor, deschideți supapa și eliberați aburul. Apăsați Anulare și deschideți capacul.",
      "Adăugați găluștele, presărați pătrunjelul proaspăt și serviți cald.",
    ],
  },
  38: {
    title: "Ciulama de pui și ciuperci",
    time: "45 min",
    servings: "4 porții",
    ingredients: [
      "700g carne de pui, tăiată cuburi",
      "50ml ulei",
      "100g făină",
      "400ml apă (poate fi omisă dacă se dorește)",
      "250g ciuperci, tăiate felii",
      "400g smântână",
      "2 cepe, tocate julien",
      "Sare și piper după gust",
      "Mămăligă pentru servit",
    ],
    instructions: [
      "Puneți uleiul în oală.",
      "Selectați Rumenire și apăsați Start.",
      "După semnalul sonor adăugați și căliți ceapa timp de 5 minute.",
      "Apoi adăugați carnea de pui și prăjiți-o timp de 5 minute. După aceea, adăugați ciupercile și căliți-le timp de 7-10 minute.",
      "Adăugați făina și amestecați timp de 5 minute (să nu se facă cocoloașe). Încorporați și smântâna, amestecând continuu, timp de încă 5 minute. (se poate adăuga un pic de apă dacă este nevoie)",
      "Apăsați Anulare.",
      "Selectați Gătire sub presiune și setați timpul la 15 minute. Închideți capacul și apăsați Start.",
      "După semnalul sonor, deschideți supapa și eliberați aburul. Apăsați Anulare și deschideți capacul.",
      "Serviți alături de mămăligă caldă.",
    ],
  },
  39: {
    title: "Orez cu lapte",
    time: "20 min",
    servings: "4 porții",
    ingredients: [
      "200g orez",
      "200ml apă",
      "500ml lapte",
      "100g zahăr",
      "Sare",
      "Vanilie",
      "Stafide",
    ],
    instructions: [
      "Puneți toate ingredientele în oală.",
      "Selectați Gătire sub presiune. Apăsați săgeata în jos și setați presiunea la Medie. Setați timpul la 15-20 minute. Închideți capacul și apăsați Start.",
      "După semnalul sonor, deschideți supapa și eliberați aburul. Apăsați Anulare și deschideți capacul.",
    ],
  },
  40: {
    title: "Pulpe de miel înăbușite",
    time: "45 min",
    servings: "4 porții",
    ingredients: [
      "4 pulpe de miel",
      "2 linguri ulei de măsline",
      "1 ceapă mare, tocată",
      "3 căței usturoi, tăiați felii",
      "2 morcovi, tăiați rondele",
      "400g roșii conservă",
      "200ml bulion de carne",
      "150ml vin roșu",
      "2 foi de dafin",
      "1 ramură rozmarin proaspăt",
      "1 linguriță oregano uscat",
      "Sare și piper",
    ],
    instructions: [
      "Condimentați pulpele de miel cu sare și piper.",
      "Selectați Rumenire și adăugați uleiul în oală.",
      "După ce uleiul s-a încins, adăugați pulpele și rumeniți-le pe toate părțile, aproximativ 8 minute. Scoateți-le și puneți-le deoparte.",
      "Adăugați ceapa și usturoiul în oală și gătiți 3 minute.",
      "Adăugați morcovii și gătiți încă 2 minute.",
      "Adăugați vinul și lăsați să fiarbă 2 minute.",
      "Adăugați roșiile, bulionul, foile de dafin, rozmarinul și oregano.",
      "Returnați pulpele de miel în oală. Apăsați Anulare.",
      "Selectați Gătire sub presiune. Setați timpul la 30 minute. Închideți capacul și apăsați Start.",
      "După semnalul sonor, eliberați presiunea și deschideți capacul.",
      "Verificați carnea - dacă nu este suficient de fragedă, selectați Gătire sub presiune încă 5-10 minute.",
      "Serviți pulpele cu sosul și legumele, alături de piure de cartofi sau orez.",
    ],
  },
  41: {
    title: "Risotto de ciuperci",
    time: "20 min",
    servings: "4 porții",
    ingredients: [
      "300g orez pentru risotto (arborio)",
      "400g ciuperci proaspete",
      "1 ceapă, tocată",
      "2 linguri ulei de măsline",
      "100ml vin alb",
      "800ml bulion de legume",
      "50g parmezan ras",
      "2 linguri unt",
      "Sare și piper",
      "Pătrunjel proaspăt",
    ],
    instructions: [
      "Curățați și felați ciupercile.",
      "Selectați Rumenire și adăugați uleiul în oală.",
      "Adăugați ceapa tocată și gătiți 3 minute până devine sticloasă.",
      "Adăugați ciupercile și gătiți încă 5 minute.",
      "Adăugați orezul și amestecați 2 minute până se înveșmântă în ulei.",
      "Adăugați vinul și lăsați să se evapore.",
      "Adăugați bulionul, sarea și piperul. Apăsați Anulare.",
      "Selectați Gătire sub presiune. Setați timpul la 7 minute. Închideți capacul și apăsați Start.",
      "După semnalul sonor, eliberați presiunea rapid.",
      "Deschideți capacul, adăugați untul și parmezanul. Amestecați bine.",
      "Decorați cu pătrunjel proaspăt și serviți imediat.",
    ],
  },
  42: {
    title: "Risotto de dovleac",
    time: "20 min",
    servings: "4 porții",
    ingredients: [
      "300g orez pentru risotto (arborio)",
      "400g dovleac, tăiat cuburi",
      "1 ceapă, tocată",
      "2 linguri ulei de măsline",
      "100ml vin alb",
      "800ml bulion de legume",
      "60g parmezan ras",
      "2 linguri unt",
      "Nucsoara",
      "Sare și piper",
      "Salvie proaspătă",
    ],
    instructions: [
      "Curățați dovleacul și tăiați-l în cuburi mici.",
      "Selectați Rumenire și adăugați uleiul.",
      "Adăugați ceapa și gătiți 3 minute.",
      "Adăugați cuburile de dovleac și gătiți 5 minute, amestecând.",
      "Adăugați orezul și amestecați 2 minute.",
      "Turnați vinul și lăsați să se evapore.",
      "Adăugați bulionul, sarea, piperul și nucșoara. Apăsați Anulare.",
      "Selectați Gătire sub presiune. Setați timpul la 7 minute. Închideți capacul și apăsați Start.",
      "După terminare, eliberați presiunea rapid.",
      "Adăugați untul și parmezanul. Amestecați până devine cremos.",
      "Decorați cu frunze de salvie și serviți cald.",
    ],
  },
  43: {
    title: "Budincă de ovăz cu ananas și mentă",
    time: "15 min",
    servings: "4 porții",
    ingredients: [
      "200g fulgi de ovăz",
      "600ml lapte",
      "200ml apă",
      "2 linguri zahăr",
      "1 linguriță esență de vanilie",
      "200g ananas proaspăt, tăiat cuburi",
      "Frunze de mentă proaspătă",
      "1 praf de sare",
    ],
    instructions: [
      "Puneți fulgii de ovăz, laptele, apa, zahărul, vanilia și sarea în oală.",
      "Amestecați bine toate ingredientele.",
      "Selectați Gătire sub presiune. Setați presiunea la Medie și timpul la 10 minute. Închideți capacul și apăsați Start.",
      "După semnalul sonor, eliberați presiunea și deschideți capacul.",
      "Amestecați budinca și lăsați să se răcească puțin.",
      "Serviți în boluri, decorați cu cuburi de ananas și frunze de mentă proaspătă.",
    ],
  },
  44: {
    title: "Budincă de ovăz",
    time: "15 min",
    servings: "4 porții",
    ingredients: [
      "200g fulgi de ovăz",
      "700ml lapte",
      "150ml apă",
      "3 linguri zahăr",
      "1 linguriță esență de vanilie",
      "1 praf de sare",
      "Scorțișoară",
      "Fructe proaspete (opțional)",
    ],
    instructions: [
      "Puneți fulgii de ovăz, laptele, apa, zahărul, vanilia și sarea în oală.",
      "Amestecați toate ingredientele.",
      "Selectați Gătire sub presiune. Setați presiunea la Medie și timpul la 10 minute. Închideți capacul și apăsați Start.",
      "După semnalul sonor, eliberați presiunea.",
      "Deschideți capacul și amestecați bine.",
      "Presărați cu scorțișoară deasupra.",
      "Serviți cald sau rece, decorat cu fructe proaspete după preferință.",
    ],
  },
  45: {
    title: "Humus",
    time: "45 min",
    servings: "6 porții",
    ingredients: [
      "300g năut uscat",
      "1L apă",
      "3 căței usturoi",
      "80ml tahini (pastă de susan)",
      "Suc de la 2 lămâi",
      "100ml ulei de măsline",
      "1 linguriță chimion",
      "Sare",
      "Boia dulce (pentru decor)",
      "Semințe de susan (pentru decor)",
    ],
    instructions: [
      "Spălați năutul și puneți-l în oală cu apa.",
      "Selectați Gătire sub presiune. Setați timpul la 40 minute. Închideți capacul și apăsați Start.",
      "După semnalul sonor, eliberați presiunea și deschideți capacul.",
      "Scurgeți năutul, păstrând 100ml din apa de fierbere.",
      "Puneți năutul într-un blender sau robot de bucătărie.",
      "Adăugați usturoiul, tahini, sucul de lămâie, chimionul și sarea.",
      "Mixați, adăugând treptat uleiul de măsline și apa păstrată, până obțineți consistența dorită.",
      "Transferați într-un bol, decorați cu boia dulce, semințe de susan și un fir de ulei de măsline.",
      "Serviți cu pâine pită sau legume crude.",
    ],
  },
};
